/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-sparkline-up-16"><path d="M10 4a1 1 0 1 0 0 2h1.586L9 8.586 6.707 6.293a1 1 0 0 0-1.414 0l-4 4a1 1 0 1 0 1.414 1.414L6 8.414l2.293 2.293a1 1 0 0 0 1.414 0L13 7.414V9a1 1 0 1 0 2 0V5a1 1 0 0 0-1-1h-4Z"/></symbol>`;

export const EbayIconSparklineUp16: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineUp16" __type="icon" __symbol={SYMBOL} />
);