/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-expand-16"><path d="M3.5 1H5a1 1 0 0 1 0 2H3.5a.5.5 0 0 0-.5.5V5a1 1 0 0 1-2 0V3.5A2.5 2.5 0 0 1 3.5 1ZM2 10a1 1 0 0 0-1 1v1.5A2.5 2.5 0 0 0 3.5 15H5a1 1 0 1 0 0-2H3.5a.5.5 0 0 1-.5-.5V11a1 1 0 0 0-1-1Zm12 0a1 1 0 0 0-1 1v1.5a.5.5 0 0 1-.5.5H11a1 1 0 1 0 0 2h1.5a2.5 2.5 0 0 0 2.5-2.5V11a1 1 0 0 0-1-1Zm0-4a1 1 0 0 0 1-1V3.5A2.5 2.5 0 0 0 12.5 1H11a1 1 0 1 0 0 2h1.5a.5.5 0 0 1 .5.5V5a1 1 0 0 0 1 1Z"/></symbol>`;

export const EbayIconExpand16: EbayIconComponent = props => (
    <EbayIcon {...props} name="expand16" __type="icon" __symbol={SYMBOL} />
);