/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-close-24"><path d="m13.41 12 7.3-7.29a1.004 1.004 0 0 0-1.42-1.42L12 10.59l-7.29-7.3a1.003 1.003 0 1 0-1.42 1.42l7.3 7.29-7.3 7.29a1.001 1.001 0 0 0 0 1.42 1.001 1.001 0 0 0 1.42 0l7.29-7.3 7.29 7.3a1.001 1.001 0 0 0 1.42 0 1.001 1.001 0 0 0 0-1.42L13.41 12Z"/></symbol>`;

export const EbayIconClose24: EbayIconComponent = props => (
    <EbayIcon {...props} name="close24" __type="icon" __symbol={SYMBOL} />
);