/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-overflow-horizontal-20"><path d="M16 11.75a1.75 1.75 0 1 1 0-3.5 1.75 1.75 0 0 1 0 3.5Zm-6 0a1.75 1.75 0 1 1 0-3.5 1.75 1.75 0 0 1 0 3.5Zm-6 0a1.75 1.75 0 1 1 0-3.5 1.75 1.75 0 0 1 0 3.5Z"/></symbol>`;

export const EbayIconOverflowHorizontal20: EbayIconComponent = props => (
    <EbayIcon {...props} name="overflowHorizontal20" __type="icon" __symbol={SYMBOL} />
);