/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 64 64" id="icon-pause-filled-64-colored"><circle cx="32" cy="32" r="32" fill="#fff" fill-opacity=".88"/><path fill-rule="evenodd" clip-rule="evenodd" d="M27 20.5a3.5 3.5 0 1 0-7 0v23a3.5 3.5 0 1 0 7 0v-23Zm17 0a3.5 3.5 0 1 0-7 0v23a3.5 3.5 0 1 0 7 0v-23Z" fill="#191919"/></symbol>`;

export const EbayIconPauseFilled64Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="pauseFilled64Colored" __type="icon" __symbol={SYMBOL} />
);