/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-desktop-24"><path d="M20 2a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3h-7v3h4a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2h4v-3H4a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3h16ZM4 4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H4Z"/></symbol>`;

export const EbayIconDesktop24: EbayIconComponent = props => (
    <EbayIcon {...props} name="desktop24" __type="icon" __symbol={SYMBOL} />
);