/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-ai-spectrum-filled-16-colored"><path d="M8.788 1.637c-.182-.85-1.394-.85-1.576 0l-.53 2.467a3.358 3.358 0 0 1-2.578 2.578l-2.467.53c-.85.182-.85 1.394 0 1.576l2.467.53a3.358 3.358 0 0 1 2.578 2.578l.53 2.467c.182.85 1.394.85 1.576 0l.53-2.467a3.358 3.358 0 0 1 2.578-2.578l2.467-.53c.85-.182.85-1.394 0-1.576l-2.467-.53a3.358 3.358 0 0 1-2.578-2.578l-.53-2.467Z" fill="url(#ref-ai-spectrum-filled-16-colored)"/><linearGradient id="ref-ai-spectrum-filled-16-colored" x1="21.21" y1="11.161" x2="11.274" y2="21.774" gradientUnits="userSpaceOnUse"><stop offset=".098" stop-color="#FFD80E"/><stop offset=".267" stop-color="#FF4242"/><stop offset=".418" stop-color="#993EE0"/><stop offset=".562" stop-color="#0968F6"/><stop offset=".785" stop-color="#4EE04B"/></linearGradient></symbol>`;

export const EbayIconAiSpectrumFilled16Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="aiSpectrumFilled16Colored" __type="icon" __symbol={SYMBOL} />
);