/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-menu-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 2a1 1 0 0 0 0 2h11a1 1 0 1 0 0-2h-11Zm-1 6a1 1 0 0 1 1-1h11a1 1 0 1 1 0 2h-11a1 1 0 0 1-1-1Zm0 5a1 1 0 0 1 1-1h11a1 1 0 1 1 0 2h-11a1 1 0 0 1-1-1Z"/></symbol>`;

export const EbayIconMenu16: EbayIconComponent = props => (
    <EbayIcon {...props} name="menu16" __type="icon" __symbol={SYMBOL} />
);