/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 30 18" id="icon-general-card-18-colored"><rect x=".5" y=".5" width="29" height="17" rx="1.5" fill="#fff" stroke="#000" stroke-width="1"/><rect x="22.25" y="13.25" width="3.5" height=".5" rx=".25" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".5"/><rect x="16.25" y="13.25" width="3.5" height=".5" rx=".25" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".5"/><rect x="10.25" y="13.25" width="3.5" height=".5" rx=".25" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".5"/><rect x="4.25" y="13.25" width="3.5" height=".5" rx=".25" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".5"/><rect x="4.5" y="5.5" width="5" height="3" rx=".5" fill="#A2A2A2" stroke="#A2A2A2"/></symbol>`;

export const EbayIconGeneralCard18Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="generalCard18Colored" __type="icon" __symbol={SYMBOL} />
);