/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-lightning-bolt-filled-24"><path d="M11.167.447A1 1 0 0 1 13 1v7h5.497c1.994 0 3.185 2.221 2.083 3.883l-7.747 11.67A1 1 0 0 1 11 23v-7H5.503c-1.994 0-3.186-2.22-2.083-3.882L11.167.448Z"/></symbol>`;

export const EbayIconLightningBoltFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="lightningBoltFilled24" __type="icon" __symbol={SYMBOL} />
);