/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-bookmark-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 4a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v18a1 1 0 0 1-1.707.707L12 16.414l-6.293 6.293A1 1 0 0 1 4 22V4Z"/></symbol>`;

export const EbayIconBookmarkFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="bookmarkFilled24" __type="icon" __symbol={SYMBOL} />
);