/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-mail-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3V5a3 3 0 0 0-3-3H4Zm13 3.47V5a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v.47l6.44 4.357a1 1 0 0 0 1.12 0L17 5.47ZM3 7.883V15a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V7.884l-5.318 3.6a3 3 0 0 1-3.363 0L3 7.884Z"/></symbol>`;

export const EbayIconMail20: EbayIconComponent = props => (
    <EbayIcon {...props} name="mail20" __type="icon" __symbol={SYMBOL} />
);