/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-grid-view-16"><path d="M6 7H1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1ZM2 5h3V3H2v2Zm13 2h-5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1Zm-4-2h3V3h-3v2ZM1 15h5a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1H1a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1Zm4-2H2v-2h3v2Zm10 2h-5a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1Zm-4-2h3v-2h-3v2Z"/></symbol>`;

export const EbayIconGridView16: EbayIconComponent = props => (
    <EbayIcon {...props} name="gridView16" __type="icon" __symbol={SYMBOL} />
);