/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-grid-view-24"><path d="M10 3H2a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1ZM9 9H3V5h6v4Zm13-6h-8a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1Zm-1 6h-6V5h6v4ZM2 13h8a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-6a1 1 0 0 1 1-1Zm1 6h6v-4H3v4Zm19-6h-8a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1Zm-1 6h-6v-4h6v4Z"/></symbol>`;

export const EbayIconGridView24: EbayIconComponent = props => (
    <EbayIcon {...props} name="gridView24" __type="icon" __symbol={SYMBOL} />
);