/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-verified-condition-24"><path d="M15.707 11.293a1 1 0 0 1 0 1.414l-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 1 1 1.414-1.414L11 14.586l3.293-3.293a1 1 0 0 1 1.414 0Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M7.416 3a5.001 5.001 0 0 1 9.168 0H18a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h1.416ZM9 5a3 3 0 1 1 6 0H9Zm8 0v1a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V5H6a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1h-1Z"/></symbol>`;

export const EbayIconVerifiedCondition24: EbayIconComponent = props => (
    <EbayIcon {...props} name="verifiedCondition24" __type="icon" __symbol={SYMBOL} />
);