/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-attention-triangle-filled-24"><path d="M8.289 3.141C9.77.319 13.797.278 15.335 3.07l7.163 13.003c1.468 2.665-.46 5.93-3.503 5.93H5.005c-3.008 0-4.94-3.195-3.541-5.858L8.289 3.14ZM12 16.003a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm0-9a1 1 0 0 0-1 1v5a1 1 0 0 0 2 0v-5a1 1 0 0 0-1-1Z"/></symbol>`;

export const EbayIconAttentionTriangleFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="attentionTriangleFilled24" __type="icon" __symbol={SYMBOL} />
);