/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-sparkline-up-20"><path d="M13 5a1 1 0 1 0 0 2h2.586L11 11.586 7.707 8.293a1 1 0 0 0-1.414 0l-5 5a1 1 0 1 0 1.414 1.414L7 10.414l3.293 3.293a1 1 0 0 0 1.414 0L17 8.414V11a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1h-5Z"/></symbol>`;

export const EbayIconSparklineUp20: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineUp20" __type="icon" __symbol={SYMBOL} />
);