/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-exclude-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.523 3.11a6 6 0 0 1 8.367 8.367L4.524 3.108ZM3.11 4.522a6 6 0 0 0 8.367 8.367L3.11 4.524ZM8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0Z"/></symbol>`;

export const EbayIconExclude16: EbayIconComponent = props => (
    <EbayIcon {...props} name="exclude16" __type="icon" __symbol={SYMBOL} />
);