/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-arrow-down-20"><path d="M2.293 9.293a1 1 0 0 1 1.414 0L9 14.586V3a1 1 0 1 1 2 0v11.586l5.293-5.293a1 1 0 1 1 1.414 1.414l-7 7a1 1 0 0 1-1.414 0l-7-7a1 1 0 0 1 0-1.414Z"/></symbol>`;

export const EbayIconArrowDown20: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowDown20" __type="icon" __symbol={SYMBOL} />
);