/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-density-compact-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 3.5A1.5 1.5 0 0 1 2.5 2h2A1.5 1.5 0 0 1 6 3.5v2A1.5 1.5 0 0 1 4.5 7h-2A1.5 1.5 0 0 1 1 5.5v-2Zm1.5 6A1.5 1.5 0 0 0 1 11v2a1.5 1.5 0 0 0 1.5 1.5h2A1.5 1.5 0 0 0 6 13v-2a1.5 1.5 0 0 0-1.5-1.5h-2Zm0 7.5A1.5 1.5 0 0 0 1 18.5v2A1.5 1.5 0 0 0 2.5 22h2A1.5 1.5 0 0 0 6 20.5v-2A1.5 1.5 0 0 0 4.5 17h-2ZM10 3.5a1 1 0 1 0 0 2h12a1 1 0 1 0 0-2H10ZM9 12a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H10a1 1 0 0 1-1-1Zm1 6.5a1 1 0 1 0 0 2h12a1 1 0 1 0 0-2H10Z"/></symbol>`;

export const EbayIconDensityCompact24: EbayIconComponent = props => (
    <EbayIcon {...props} name="densityCompact24" __type="icon" __symbol={SYMBOL} />
);