/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-youtube-24"><path d="M23.498 6.185a3.016 3.016 0 0 0-2.122-2.135C19.506 3.545 12 3.545 12 3.545s-7.505 0-9.376.505A3.016 3.016 0 0 0 .502 6.185C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.872.505 9.376.505 9.376.505s7.506 0 9.376-.505a3.016 3.016 0 0 0 2.122-2.136C24 15.931 24 12 24 12s0-3.93-.502-5.815ZM9.545 15.57V8.43L15.818 12l-6.273 3.569Z"/></symbol>`;

export const EbayIconYoutube24: EbayIconComponent = props => (
    <EbayIcon {...props} name="youtube24" __type="icon" __symbol={SYMBOL} />
);