/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-yuan-24"><path d="M3.774 1.367a1 1 0 0 0-1.548 1.266L10.708 13H6a1 1 0 1 0 0 2h5v2H6a1 1 0 1 0 0 2h5v3a1 1 0 1 0 2 0v-3h5a1 1 0 1 0 0-2h-5v-2h5a1 1 0 1 0 0-2h-4.708l8.482-10.367a1 1 0 1 0-1.548-1.266L12 11.42 3.774 1.367Z"/></symbol>`;

export const EbayIconYuan24: EbayIconComponent = props => (
    <EbayIcon {...props} name="yuan24" __type="icon" __symbol={SYMBOL} />
);