/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 35 25" fill="none" id="icon-ccd-top"><path d="M0.5 25V13.5H34.5V25" stroke-width="1"/><path d="M6.5 13V0.5H10.5V13" stroke-width="1"/><path d="M24.5 13V0.5H28.5V13" stroke-width="1"/></symbol>`;

export const EbayIconCcdTop: EbayIconComponent = props => (
    <EbayIcon {...props} name="ccdTop" __type="icon" __symbol={SYMBOL} />
);