/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-sparkline-down-20"><path d="M13 15a1 1 0 1 1 0-2h2.586L11 8.414l-3.293 3.293a1 1 0 0 1-1.414 0l-5-5a1 1 0 0 1 1.414-1.414L7 9.586l3.293-3.293a1 1 0 0 1 1.414 0L17 11.586V9a1 1 0 1 1 2 0v5a1 1 0 0 1-1 1h-5Z"/></symbol>`;

export const EbayIconSparklineDown20: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineDown20" __type="icon" __symbol={SYMBOL} />
);