/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-zoom-in-16"><path d="M7 4.5a.5.5 0 0 0-1 0V6H4.5a.5.5 0 0 0 0 1H6v1.5a.5.5 0 0 0 1 0V7h1.5a.5.5 0 0 0 0-1H7V4.5Z"/><path d="m14.739 13.34.021.01a1 1 0 0 1-1.41 1.41l-3.732-3.732A5.47 5.47 0 0 1 6.5 12 5.5 5.5 0 1 1 12 6.5c0 1.174-.37 2.259-.996 3.151l.025.008 3.71 3.681ZM6.5 3a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z"/></symbol>`;

export const EbayIconZoomIn16: EbayIconComponent = props => (
    <EbayIcon {...props} name="zoomIn16" __type="icon" __symbol={SYMBOL} />
);