/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-unlock-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.08 6.199A4.002 4.002 0 0 1 16 7v2H6a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3v-8a3 3 0 0 0-3-3V7A6 6 0 0 0 6.12 5.801a1 1 0 0 0 1.96.398ZM17 11H6a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-8a1 1 0 0 0-1-1h-1Zm-5 2a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0v-4a1 1 0 0 1 1-1Z"/></symbol>`;

export const EbayIconUnlock24: EbayIconComponent = props => (
    <EbayIcon {...props} name="unlock24" __type="icon" __symbol={SYMBOL} />
);