/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-panel-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 6a1 1 0 0 1 1-1h3.997v14H4a1 1 0 0 1-1-1V6Zm6.997 13h10.001a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1h-10v14ZM4 3a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h15.998a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3H4Z"/></symbol>`;

export const EbayIconPanel24: EbayIconComponent = props => (
    <EbayIcon {...props} name="panel24" __type="icon" __symbol={SYMBOL} />
);