/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-large-box-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.9 4.8A2 2 0 0 1 5.5 4h13a2 2 0 0 1 1.6.8l2.3 3.067a3 3 0 0 1 .6 1.8V17a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V9.667a3 3 0 0 1 .6-1.8L3.9 4.8ZM18.5 6H13v2h7l-1.5-2Zm2.5 4h-8v8h7a1 1 0 0 0 1-1v-7ZM11 8V6H5.5L4 8h7Zm-8 2h8v8H4a1 1 0 0 1-1-1v-7Z"/></symbol>`;

export const EbayIconLargeBox24: EbayIconComponent = props => (
    <EbayIcon {...props} name="largeBox24" __type="icon" __symbol={SYMBOL} />
);