/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-ruler-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H7v7a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2Zm11 3V4a1 1 0 1 0-2 0v1H7V4a1 1 0 0 0-2 0v1H4a1 1 0 0 0 0 2h1v2H4a1 1 0 1 0 0 2h1v3H2V2h12v3h-3Z"/></symbol>`;

export const EbayIconRuler16: EbayIconComponent = props => (
    <EbayIcon {...props} name="ruler16" __type="icon" __symbol={SYMBOL} />
);