/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-split-payment-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 3a1 1 0 0 0 0-2H2a1 1 0 0 0-1 1v6a1 1 0 0 0 2 0V4.414l7.121 7.122a3 3 0 0 1 .879 2.12V22a1 1 0 1 0 2 0v-8.343a5 5 0 0 0-1.464-3.536L4.414 3H8Zm13 1.414V8a1 1 0 1 0 2 0V2a1 1 0 0 0-1-1h-6a1 1 0 1 0 0 2h3.586l-5.293 5.293a1 1 0 0 0 1.414 1.414L21 4.414Z"/></symbol>`;

export const EbayIconSplitPayment24: EbayIconComponent = props => (
    <EbayIcon {...props} name="splitPayment24" __type="icon" __symbol={SYMBOL} />
);