/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-move-24"><path d="M18.71 17.29 7.48 6H17a1 1 0 0 0 0-2H5a1 1 0 0 0-1 1v12a1 1 0 0 0 2 0V7.35l11.29 11.36A.999.999 0 0 0 18 19a.999.999 0 0 0 .71-1.71Z"/></symbol>`;

export const EbayIconMove24: EbayIconComponent = props => (
    <EbayIcon {...props} name="move24" __type="icon" __symbol={SYMBOL} />
);