/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-money-back-guarantee-filled-24"><path d="M10.852.348a2.069 2.069 0 0 1 2.296 0c3.296 2.204 6.483 2.909 7.578 3.097A1.53 1.53 0 0 1 22 4.945v6.04c0 2.788-.571 5.186-2.059 7.316-1.473 2.11-3.778 3.86-7.063 5.49a1.98 1.98 0 0 1-1.756 0c-3.285-1.63-5.59-3.38-7.063-5.49C2.57 16.171 2 13.773 2 10.986v-6.04c0-.769.57-1.38 1.274-1.501 1.095-.188 4.282-.893 7.578-3.097Zm5.859 8.271a1 1 0 0 0-1.414 0l-4.632 4.631-1.962-1.962a1 1 0 0 0-1.414 1.415l2.669 2.67a1 1 0 0 0 1.414 0l5.339-5.34a1 1 0 0 0 0-1.414Z"/></symbol>`;

export const EbayIconMoneyBackGuaranteeFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="moneyBackGuaranteeFilled24" __type="icon" __symbol={SYMBOL} />
);