/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-full-view-24"><path d="M22 3H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h20a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1Zm-1 12H3V5h18v10ZM2 19h20a1 1 0 0 1 0 2H2a1 1 0 0 1 0-2Z"/></symbol>`;

export const EbayIconFullView24: EbayIconComponent = props => (
    <EbayIcon {...props} name="fullView24" __type="icon" __symbol={SYMBOL} />
);