/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-search-similar-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M6 2a1 1 0 0 0-1-1H3.5A2.5 2.5 0 0 0 1 3.5V5a1 1 0 0 0 2 0V3.5a.5.5 0 0 1 .5-.5H5a1 1 0 0 0 1-1Zm9 3a1 1 0 1 1-2 0V3.5a.5.5 0 0 0-.5-.5H11a1 1 0 1 1 0-2h1.5A2.5 2.5 0 0 1 15 3.5V5ZM3 11a1 1 0 1 0-2 0v1.5A2.5 2.5 0 0 0 3.5 15H5a1 1 0 1 0 0-2H3.5a.5.5 0 0 1-.5-.5V11Zm5-1a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0 2c.742 0 1.436-.202 2.032-.554l2.26 2.261a1 1 0 0 0 1.415-1.414l-2.26-2.261A4 4 0 1 0 8 12Z"/></symbol>`;

export const EbayIconSearchSimilar16: EbayIconComponent = props => (
    <EbayIcon {...props} name="searchSimilar16" __type="icon" __symbol={SYMBOL} />
);