/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-arrow-down-24"><path d="M11 3v15.585l-6.287-6.298a1.002 1.002 0 0 0-1.679.45c-.093.347.006.716.26.97l7.996 7.997a1 1 0 0 0 1.419 0l7.995-7.998a1.001 1.001 0 0 0 0-1.42 1 1 0 0 0-1.419 0l-6.286 6.299V3a1 1 0 0 0-2 0Z"/></symbol>`;

export const EbayIconArrowDown24: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowDown24" __type="icon" __symbol={SYMBOL} />
);