/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-clock-12"><path d="M6.75 3.75v1.942l1.275 1.283a.75.75 0 0 1-1.058 1.058l-1.5-1.5A.75.75 0 0 1 5.25 6V3.75a.75.75 0 0 1 1.5 0Z"/><path d="M6 0a6 6 0 1 0 0 12A6 6 0 0 0 6 0Zm0 10.5a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9Z"/></symbol>`;

export const EbayIconClock12: EbayIconComponent = props => (
    <EbayIcon {...props} name="clock12" __type="icon" __symbol={SYMBOL} />
);