/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chevron-left-24"><path d="m6.293 11.292 8-8a1 1 0 1 1 1.414 1.415L8.414 12l7.293 7.293a1 1 0 1 1-1.414 1.414l-8-8a.996.996 0 0 1 0-1.415Z"/></symbol>`;

export const EbayIconChevronLeft24: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronLeft24" __type="icon" __symbol={SYMBOL} />
);