/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-arrow-up-24"><path d="m11.29 2.296-7.996 7.998a1.004 1.004 0 0 0 1.419 1.42L11 5.414V21a1 1 0 0 0 1.998 0V5.415l6.287 6.298a1 1 0 0 0 1.42 0 1.001 1.001 0 0 0 0-1.42l-7.996-7.997a1 1 0 0 0-1.42 0Z"/></symbol>`;

export const EbayIconArrowUp24: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowUp24" __type="icon" __symbol={SYMBOL} />
);