/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chevron-up-24"><path d="m12.707 6.293 8 8a1 1 0 0 1-1.414 1.414L12 8.414l-7.293 7.293a1 1 0 0 1-1.414-1.414l8-8a1 1 0 0 1 1.414 0Z"/></symbol>`;

export const EbayIconChevronUp24: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronUp24" __type="icon" __symbol={SYMBOL} />
);