/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-density-compact-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.8 1.5a.8.8 0 0 0-.8.8v1.4a.8.8 0 0 0 .8.8h1.4a.8.8 0 0 0 .8-.8V2.3a.8.8 0 0 0-.8-.8H1.8ZM7 2a1 1 0 0 0 0 2h7a1 1 0 1 0 0-2H7Zm0 5a1 1 0 0 0 0 2h7a1 1 0 1 0 0-2H7Zm-1 6a1 1 0 0 1 1-1h7a1 1 0 1 1 0 2H7a1 1 0 0 1-1-1ZM1 7.3a.8.8 0 0 1 .8-.8h1.4a.8.8 0 0 1 .8.8v1.4a.8.8 0 0 1-.8.8H1.8a.8.8 0 0 1-.8-.8V7.3Zm.8 4.2a.8.8 0 0 0-.8.8v1.4a.8.8 0 0 0 .8.8h1.4a.8.8 0 0 0 .8-.8v-1.4a.8.8 0 0 0-.8-.8H1.8Z"/></symbol>`;

export const EbayIconDensityCompact16: EbayIconComponent = props => (
    <EbayIcon {...props} name="densityCompact16" __type="icon" __symbol={SYMBOL} />
);