/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-feedback-neutral-16"><path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0ZM6.125 5.125a1 1 0 0 0-1 1v3.75a1 1 0 0 0 1 1h3.75a1 1 0 0 0 1-1v-3.75a1 1 0 0 0-1-1h-3.75Z"/></symbol>`;

export const EbayIconFeedbackNeutral16: EbayIconComponent = props => (
    <EbayIcon {...props} name="feedbackNeutral16" __type="icon" __symbol={SYMBOL} />
);