/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-key-16"><path d="M6 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M9.584 10A5 5 0 1 1 9 5h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-3a1 1 0 0 1-1-1v-1H9.584ZM2 8a3 3 0 0 1 5.556-1.571A1 1 0 0 0 8.484 7H14v3h-1V9a1 1 0 0 0-1-1H8.895a1 1 0 0 0-1.01.826A3.002 3.002 0 0 1 2 8Z"/></symbol>`;

export const EbayIconKey16: EbayIconComponent = props => (
    <EbayIcon {...props} name="key16" __type="icon" __symbol={SYMBOL} />
);