/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-undo-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M13 8a5 5 0 0 0-5-5c-1.514 0-2.78.666-3.875 2H6a1 1 0 1 1 0 2H2.268a.98.98 0 0 1-.038 0H2a1 1 0 0 1-1-1V2a1 1 0 1 1 2 0v1.255C4.312 1.86 5.95 1 8 1a7 7 0 1 1-6.063 10.5 1 1 0 1 1 1.731-1A5 5 0 0 0 13 8Z"/></symbol>`;

export const EbayIconUndo16: EbayIconComponent = props => (
    <EbayIcon {...props} name="undo16" __type="icon" __symbol={SYMBOL} />
);