/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-masonry-view-24"><path fill-rule="evenodd" d="M3 5V3h6v2H3ZM1 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2Zm14 11V3h6v10h-6ZM13 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-8a1 1 0 0 1-1-1V2Zm2 17v2h6v-2h-6Zm-1-2a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1h-8ZM3 21V11h6v10H3ZM1 10a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V10Z"/></symbol>`;

export const EbayIconMasonryView24: EbayIconComponent = props => (
    <EbayIcon {...props} name="masonryView24" __type="icon" __symbol={SYMBOL} />
);