/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-location-arrow-16"><path fill-rule="evenodd" clip-rule="evenodd" d="m12.352 3.647-7.672 3.2 2.87.673c.461.108.822.47.93.931l.674 2.868 3.198-7.672Zm.913-2.547c1.03-.43 2.064.604 1.635 1.635l-4.793 11.494c-.467 1.12-2.094.986-2.37-.195L6.64 9.36 1.965 8.265C.785 7.988.65 6.36 1.769 5.895L13.265 1.1Z"/></symbol>`;

export const EbayIconLocationArrow16: EbayIconComponent = props => (
    <EbayIcon {...props} name="locationArrow16" __type="icon" __symbol={SYMBOL} />
);