/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-transaction-24"><path d="m21.707 6.707-4 4a1 1 0 0 1-1.414-1.414L18.586 7H3a1 1 0 0 1 0-2h15.586l-2.293-2.293a1 1 0 0 1 1.414-1.414l4 4a1 1 0 0 1 0 1.414ZM6.293 13.293a1 1 0 0 1 1.414 1.414L5.414 17H21a1 1 0 1 1 0 2H5.414l2.293 2.293a1 1 0 1 1-1.414 1.414l-4-4a.999.999 0 0 1 0-1.414l4-4Z"/></symbol>`;

export const EbayIconTransaction24: EbayIconComponent = props => (
    <EbayIcon {...props} name="transaction24" __type="icon" __symbol={SYMBOL} />
);