/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-play-filled-16-colored"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16Z" fill="#fff" fill-opacity=".88"/><path d="M11.514 8.857a1 1 0 0 0 0-1.714l-5-3A1 1 0 0 0 5 5v6a1 1 0 0 0 1.514.857l5-3Z" fill="#191919"/></symbol>`;

export const EbayIconPlayFilled16Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="playFilled16Colored" __type="icon" __symbol={SYMBOL} />
);