/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-bar-chart-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M15 14a1 1 0 1 1-2 0V5a1 1 0 1 1 2 0v9Zm-8 0a1 1 0 1 1-2 0V8a1 1 0 1 1 2 0v6Zm3 1a1 1 0 0 0 1-1V1a1 1 0 1 0-2 0v13a1 1 0 0 0 1 1Zm-7-1a1 1 0 1 1-2 0V5a1 1 0 1 1 2 0v9Z"/></symbol>`;

export const EbayIconBarChart16: EbayIconComponent = props => (
    <EbayIcon {...props} name="barChart16" __type="icon" __symbol={SYMBOL} />
);