/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-panel-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 4a.5.5 0 0 1 .5-.5H5v9H2.5A.5.5 0 0 1 2 12V4Zm5 8.5h6.5a.5.5 0 0 0 .5-.5V4a.5.5 0 0 0-.5-.5H7v9Zm-4.5-11A2.5 2.5 0 0 0 0 4v8a2.5 2.5 0 0 0 2.5 2.5h11A2.5 2.5 0 0 0 16 12V4a2.5 2.5 0 0 0-2.5-2.5h-11Z"/></symbol>`;

export const EbayIconPanel16: EbayIconComponent = props => (
    <EbayIcon {...props} name="panel16" __type="icon" __symbol={SYMBOL} />
);