/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-pause-24"><path d="M9 5a2 2 0 1 0-4 0v14a2 2 0 1 0 4 0V5Zm10 0a2 2 0 1 0-4 0v14a2 2 0 1 0 4 0V5Z"/></symbol>`;

export const EbayIconPause24: EbayIconComponent = props => (
    <EbayIcon {...props} name="pause24" __type="icon" __symbol={SYMBOL} />
);