/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 64 64" id="icon-chat-64"><path d="M23 29a5 5 0 1 1-10 0 5 5 0 0 1 10 0Zm9 5a5 5 0 1 0 0-10 5 5 0 0 0 0 10Zm19-5a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z"/><path d="M30.447 50H12a9 9 0 0 1-9-9V17a9 9 0 0 1 9-9h40a9 9 0 0 1 9 9v24a9 9 0 0 1-8 8.945V56c0 4.026-4.515 6.401-7.833 4.12L30.447 50ZM52 13H12a4 4 0 0 0-4 4v24a4 4 0 0 0 4 4h20l16 11V45h4a4 4 0 0 0 4-4V17a4 4 0 0 0-4-4Z"/></symbol>`;

export const EbayIconChat64: EbayIconComponent = props => (
    <EbayIcon {...props} name="chat64" __type="icon" __symbol={SYMBOL} />
);