/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-list-view-24"><path d="M3 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm19 1H7a1 1 0 0 1 0-2h15a1 1 0 0 1 0 2ZM2 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm5-2h15a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2ZM2 21a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm5-2h15a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2Z"/></symbol>`;

export const EbayIconListView24: EbayIconComponent = props => (
    <EbayIcon {...props} name="listView24" __type="icon" __symbol={SYMBOL} />
);