/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-calendar-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M18 1a1 1 0 0 1 1 1v1h1a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h1V2a1 1 0 0 1 2 0v1h10V2a1 1 0 0 1 1-1ZM6 5H4a1 1 0 0 0-1 1v1h18V6a1 1 0 0 0-1-1H6ZM3 9v11a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9H3Zm12 3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2Zm-4-1a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-2Zm-6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-2Z"/></symbol>`;

export const EbayIconCalendar24: EbayIconComponent = props => (
    <EbayIcon {...props} name="calendar24" __type="icon" __symbol={SYMBOL} />
);