/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-filter-24"><path d="M3 7a1 1 0 0 1 1-1h16a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1Zm3 5a1 1 0 0 1 1-1h10a1 1 0 1 1 0 2H7a1 1 0 0 1-1-1Zm4 4a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2h-4Z"/></symbol>`;

export const EbayIconFilter24: EbayIconComponent = props => (
    <EbayIcon {...props} name="filter24" __type="icon" __symbol={SYMBOL} />
);