/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-share-ios-20"><path d="M10.707.293a1 1 0 0 0-1.414 0l-3 3a1 1 0 0 0 1.414 1.414L9 3.414V12a1 1 0 1 0 2 0V3.414l1.293 1.293a1 1 0 1 0 1.414-1.414l-3-3Z"/><path d="M5 9.5a.5.5 0 0 1 .5-.5H6a1 1 0 1 0 0-2h-.5A2.5 2.5 0 0 0 3 9.5V16a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V9.5A2.5 2.5 0 0 0 14.5 7H14a1 1 0 1 0 0 2h.5a.5.5 0 0 1 .5.5V16a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V9.5Z"/></symbol>`;

export const EbayIconShareIos20: EbayIconComponent = props => (
    <EbayIcon {...props} name="shareIos20" __type="icon" __symbol={SYMBOL} />
);