/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-item-list-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.25 1A2.25 2.25 0 0 0 1 3.25v3.5A2.25 2.25 0 0 0 3.25 9h3.5A2.25 2.25 0 0 0 9 6.75v-3.5A2.25 2.25 0 0 0 6.75 1h-3.5ZM3 3.25A.25.25 0 0 1 3.25 3h3.5a.25.25 0 0 1 .25.25v3.5a.25.25 0 0 1-.25.25h-3.5A.25.25 0 0 1 3 6.75v-3.5ZM3.25 11A2.25 2.25 0 0 0 1 13.25v3.5A2.25 2.25 0 0 0 3.25 19h3.5A2.25 2.25 0 0 0 9 16.75v-3.5A2.25 2.25 0 0 0 6.75 11h-3.5ZM3 13.25a.25.25 0 0 1 .25-.25h3.5a.25.25 0 0 1 .25.25v3.5a.25.25 0 0 1-.25.25h-3.5a.25.25 0 0 1-.25-.25v-3.5ZM11 3a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1Zm1 2a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2h-4Zm-1 8a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1Zm1 2a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2h-4Z"/></symbol>`;

export const EbayIconItemList20: EbayIconComponent = props => (
    <EbayIcon {...props} name="itemList20" __type="icon" __symbol={SYMBOL} />
);