/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-arrow-left-12"><path d="M1.211 5.477 5.5 1.207a.717.717 0 0 1 1.01.003.71.71 0 0 1-.003 1.007L3.434 5.271h6.852a.713.713 0 1 1 0 1.423H3.434l3.072 3.054a.71.71 0 0 1-.298 1.232.716.716 0 0 1-.71-.229l-4.287-4.27a.71.71 0 0 1 0-1.004Z"/></symbol>`;

export const EbayIconArrowLeft12: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowLeft12" __type="icon" __symbol={SYMBOL} />
);