/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-video-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 3a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h14a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3H5ZM4 6a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6Zm11.671 5.435-5.6-3.333C9.605 7.825 9 8.144 9 8.668v6.664c0 .524.605.843 1.071.566l5.6-3.333a.65.65 0 0 0 0-1.13Z"/></symbol>`;

export const EbayIconVideo24: EbayIconComponent = props => (
    <EbayIcon {...props} name="video24" __type="icon" __symbol={SYMBOL} />
);