/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-upload-16"><path d="M3.293 6.707a1 1 0 0 0 1.414 0L7 4.414V10a1 1 0 1 0 2 0V4.414l2.293 2.293a1 1 0 1 0 1.414-1.414l-4-4a1 1 0 0 0-1.414 0l-4 4a1 1 0 0 0 0 1.414ZM1 14a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H2a1 1 0 0 1-1-1Z"/></symbol>`;

export const EbayIconUpload16: EbayIconComponent = props => (
    <EbayIcon {...props} name="upload16" __type="icon" __symbol={SYMBOL} />
);