/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-remove-16"><path d="M13 7H3a1 1 0 0 0 0 2h10a1 1 0 0 0 0-2Z"/></symbol>`;

export const EbayIconRemove16: EbayIconComponent = props => (
    <EbayIcon {...props} name="remove16" __type="icon" __symbol={SYMBOL} />
);