/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-search-24"><path d="M3 10a7 7 0 1 1 14 0 7 7 0 0 1-14 0Zm19.703 11.29-5.67-5.67-.008-.003A8.954 8.954 0 0 0 19 10a9 9 0 0 0-9-9 9 9 0 0 0-9 9 9 9 0 0 0 9 9 8.958 8.958 0 0 0 5.66-2.007l5.663 5.717c.19.187.445.292.71.29a1 1 0 0 0 .67-1.71Z"/></symbol>`;

export const EbayIconSearch24: EbayIconComponent = props => (
    <EbayIcon {...props} name="search24" __type="icon" __symbol={SYMBOL} />
);