/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-flag-24"><path fill-rule="evenodd" d="M20.777 1.37a.999.999 0 0 1-.207 1.452L14.72 7l5.832 4.166A.999.999 0 0 1 19.979 13H7v9a1 1 0 1 1-2 0V2a1 1 0 0 1 1-1h13.987a1.001 1.001 0 0 1 .79.37ZM16.88 11l-4.46-3.186a1 1 0 0 1 0-1.628L16.879 3H7v8h9.879Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconFlag24: EbayIconComponent = props => (
    <EbayIcon {...props} name="flag24" __type="icon" __symbol={SYMBOL} />
);