/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-profile-verification-20"><path d="M10 10a7.65 7.65 0 0 1 3.715.959 1 1 0 1 1-.97 1.749A5.65 5.65 0 0 0 10 12c-2.78 0-5.376 2.273-5.902 5H9a1 1 0 1 1 0 2H3.75c-.93 0-1.83-.781-1.697-1.87l.052-.358C2.741 13.076 6.167 10 10 10Zm6.793 3.293a1 1 0 0 1 1.414 1.414l-3.333 3.333a1 1 0 0 1-1.414 0l-1.667-1.666a1 1 0 0 1 1.414-1.414l.959.959 2.627-2.626ZM10 1a4 4 0 1 1 0 8 4 4 0 0 1 0-8Zm0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/></symbol>`;

export const EbayIconProfileVerification20: EbayIconComponent = props => (
    <EbayIcon {...props} name="profileVerification20" __type="icon" __symbol={SYMBOL} />
);