/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-bookmark-filled-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 3.5A2.5 2.5 0 0 1 5.5 1h5A2.5 2.5 0 0 1 13 3.5V14a1 1 0 0 1-1.707.707L8 11.414l-3.293 3.293A1 1 0 0 1 3 14V3.5Z"/></symbol>`;

export const EbayIconBookmarkFilled16: EbayIconComponent = props => (
    <EbayIcon {...props} name="bookmarkFilled16" __type="icon" __symbol={SYMBOL} />
);