/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-external-link-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.586 3 7.293 7.293a1 1 0 0 0 1.414 1.414L13 4.414V6a1 1 0 1 0 2 0V1.997A.997.997 0 0 0 14 1h-4a1 1 0 1 0 0 2h1.586ZM1 5.5A2.5 2.5 0 0 1 3.5 3H6a1 1 0 0 1 0 2H3.5a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V10a1 1 0 1 1 2 0v2.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 1 12.5v-7Z"/></symbol>`;

export const EbayIconExternalLink16: EbayIconComponent = props => (
    <EbayIcon {...props} name="externalLink16" __type="icon" __symbol={SYMBOL} />
);