/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-euro-24"><path d="M6.573 9c1.172-2.936 4.012-5 7.316-5 2.575 0 4.865 1.25 6.308 3.196a1 1 0 1 0 1.606-1.192C20.003 3.577 17.13 2 13.888 2 9.454 2 5.713 4.949 4.454 9H2a1 1 0 0 0 0 2h2.049a10.333 10.333 0 0 0 0 2H2a1 1 0 1 0 0 2h2.453c1.259 4.052 5 7 9.436 7 3.24 0 6.114-1.577 7.914-4.004a1 1 0 1 0-1.606-1.192C18.754 18.75 16.464 20 13.889 20c-3.304 0-6.144-2.064-7.316-5H13a1 1 0 1 0 0-2H6.06a8.318 8.318 0 0 1 0-2H15a1 1 0 1 0 0-2H6.573Z"/></symbol>`;

export const EbayIconEuro24: EbayIconComponent = props => (
    <EbayIcon {...props} name="euro24" __type="icon" __symbol={SYMBOL} />
);