/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-keyboard-16"><path fill-rule="evenodd" d="M0 4.5A2.5 2.5 0 0 1 2.5 2h11A2.5 2.5 0 0 1 16 4.5v7a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 0 11.5v-7ZM2.5 4a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5h-11Z" clip-rule="evenodd"/><rect width="8" height="2" x="4" y="9" rx="1"/><rect width="2" height="2" x="11" y="5" rx=".5"/><rect width="2" height="2" x="7" y="5" rx=".5"/><rect width="2" height="2" x="3" y="5" rx=".5"/></symbol>`;

export const EbayIconKeyboard16: EbayIconComponent = props => (
    <EbayIcon {...props} name="keyboard16" __type="icon" __symbol={SYMBOL} />
);