/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-play-disabled-16"><path d="M9.118 12.218 4.836 14.82c-.8.486-1.836-.073-1.836-.989V8.284l6.118 3.934ZM3 2.168c0-.916 1.037-1.475 1.836-.99l9.6 5.832a1.15 1.15 0 0 1 0 1.978l-2.063 1.252 2.174 1.422.083.06a1 1 0 0 1-1.089 1.666l-.088-.052-13-8.5-.083-.06A1 1 0 0 1 1.46 3.11l.088.052L3 4.112V2.167Z"/></symbol>`;

export const EbayIconPlayDisabled16: EbayIconComponent = props => (
    <EbayIcon {...props} name="playDisabled16" __type="icon" __symbol={SYMBOL} />
);