/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-ai-filled-20"><path d="M8.987 1.819c.234-1.092 1.792-1.092 2.026 0l.681 3.172a4.317 4.317 0 0 0 3.315 3.315l3.172.681c1.092.234 1.092 1.792 0 2.026l-3.172.681a4.317 4.317 0 0 0-3.315 3.315l-.681 3.172c-.234 1.092-1.792 1.092-2.026 0l-.681-3.172a4.317 4.317 0 0 0-3.315-3.315l-3.172-.681c-1.092-.234-1.092-1.792 0-2.026l3.172-.681A4.317 4.317 0 0 0 8.306 4.99l.681-3.172Z"/></symbol>`;

export const EbayIconAiFilled20: EbayIconComponent = props => (
    <EbayIcon {...props} name="aiFilled20" __type="icon" __symbol={SYMBOL} />
);