/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-sparkline-up-24"><path d="M16 6a1 1 0 1 0 0 2h3.586L13 14.586l-4.293-4.293a1 1 0 0 0-1.414 0l-6 6a1 1 0 1 0 1.414 1.414L8 12.414l4.293 4.293a1 1 0 0 0 1.414 0L21 9.414V13a1 1 0 1 0 2 0V7a1 1 0 0 0-1-1h-6Z"/></symbol>`;

export const EbayIconSparklineUp24: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineUp24" __type="icon" __symbol={SYMBOL} />
);