/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-top-service-filled-24"><path d="M19 0a3 3 0 0 1 3 3v17.99c0 2.42-2.72 3.844-4.71 2.464l-4.717-3.271a1 1 0 0 0-1.14 0L6.71 23.457C4.719 24.837 2 23.413 2 20.992V3a3 3 0 0 1 3-3h14Zm-5.713 4.736a1.5 1.5 0 0 0-2.574 0l-1.26 2.109-2.283.512a1.5 1.5 0 0 0-.816 2.433l1.51 1.787-.33 2.742c-.146 1.21 1.135 2.08 2.205 1.498L12 14.59l2.26 1.228c1.071.582 2.351-.288 2.206-1.498l-.33-2.742 1.51-1.787a1.5 1.5 0 0 0-.816-2.433l-2.282-.512-1.26-2.109Zm-.257 3.466a1.1 1.1 0 0 0 .702.509l1.855.417-1.232 1.457a1.1 1.1 0 0 0-.253.842l.262 2.17-1.839-1a1.1 1.1 0 0 0-1.05 0l-1.84 1 .261-2.17a1.1 1.1 0 0 0-.251-.842L8.413 9.128l1.855-.417a1.1 1.1 0 0 0 .702-.509L12 6.48l1.03 1.722Z"/></symbol>`;

export const EbayIconTopServiceFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="topServiceFilled24" __type="icon" __symbol={SYMBOL} />
);