/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-swap-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.207.793a1 1 0 1 0-1.414 1.414L15.586 4H8a7 7 0 0 0-7 7v4a1 1 0 1 0 2 0v-4a5 5 0 0 1 5-5h7.586l-1.793 1.793a1 1 0 0 0 1.414 1.414l3.5-3.5a1 1 0 0 0 0-1.414l-3.5-3.5Zm-5 15.414a1 1 0 0 0-1.414-1.414l-3.5 3.5a1 1 0 0 0 0 1.414l3.5 3.5a1 1 0 0 0 1.414-1.414L8.414 20H16a7 7 0 0 0 7-7V9a1 1 0 1 0-2 0v4a5 5 0 0 1-5 5H8.414l1.793-1.793Z"/></symbol>`;

export const EbayIconSwap24: EbayIconComponent = props => (
    <EbayIcon {...props} name="swap24" __type="icon" __symbol={SYMBOL} />
);