/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-arrow-left-16"><path d="M14 7H4.41l4.3-4.29a1.004 1.004 0 0 0-1.42-1.42l-6 6a1 1 0 0 0 0 1.41l6 6a1 1 0 0 0 1.41-1.41L4.41 9H14a1 1 0 1 0 0-2Z"/></symbol>`;

export const EbayIconArrowLeft16: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowLeft16" __type="icon" __symbol={SYMBOL} />
);