/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-density-default-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 4.8a.8.8 0 0 1 .8-.8h1.4a.8.8 0 0 1 .8.8v1.4a.8.8 0 0 1-.8.8H1.8a.8.8 0 0 1-.8-.8V4.8Zm6-.3a1 1 0 0 0 0 2h7a1 1 0 1 0 0-2H7Zm0 5a1 1 0 1 0 0 2h7a1 1 0 1 0 0-2H7ZM1.8 9a.8.8 0 0 0-.8.8v1.4a.8.8 0 0 0 .8.8h1.4a.8.8 0 0 0 .8-.8V9.8a.8.8 0 0 0-.8-.8H1.8Z"/></symbol>`;

export const EbayIconDensityDefault16: EbayIconComponent = props => (
    <EbayIcon {...props} name="densityDefault16" __type="icon" __symbol={SYMBOL} />
);