/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-pin-filled-24"><path d="M19.51 7.372a1 1 0 0 0 .98-1.743l-8-4.5a1 1 0 0 0-.98 1.743l.53.299-2.752 5.046L6.274 9.51a1.5 1.5 0 0 0-.75.708l-.876 1.75a1.1 1.1 0 0 0 .45 1.454l3.532 1.962-3.498 6.121a1 1 0 1 0 1.736.992l3.51-6.142 3.545 1.97a1.1 1.1 0 0 0 1.518-.47l.883-1.767a1.5 1.5 0 0 0 .144-.883l-.429-3 2.98-5.108.49.276Z"/></symbol>`;

export const EbayIconPinFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="pinFilled24" __type="icon" __symbol={SYMBOL} />
);