/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-lock-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 7a4 4 0 1 1 8 0v2H8V7ZM6 9V7a6 6 0 1 1 12 0v2a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3v-8a3 3 0 0 1 3-3Zm6 4a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0v-4a1 1 0 0 1 1-1Z"/></symbol>`;

export const EbayIconLockFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="lockFilled24" __type="icon" __symbol={SYMBOL} />
);