/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-checkmark-24"><path fill-rule="evenodd" d="M22.68 4.267a1 1 0 0 1 .053 1.413l-13 14a1 1 0 0 1-1.44.027l-7-7a1 1 0 1 1 1.414-1.414l6.266 6.266L21.267 4.32a1 1 0 0 1 1.413-.052Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconCheckmark24: EbayIconComponent = props => (
    <EbayIcon {...props} name="checkmark24" __type="icon" __symbol={SYMBOL} />
);