/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-sharpen-24"><path fill-rule="evenodd" d="M12.893 2.553a1 1 0 0 0-1.79 0l-8.996 18A1 1 0 0 0 3.002 22h17.996a1 1 0 0 0 .895-1.448l-9-17.999Zm6.486 17.446L12 5.238 4.62 19.999h14.76Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconSharpen24: EbayIconComponent = props => (
    <EbayIcon {...props} name="sharpen24" __type="icon" __symbol={SYMBOL} />
);