/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-top-rated-seller-16"><path fill-rule="evenodd" d="M4 1a1 1 0 0 0-1 1v1H1a1 1 0 0 0-1 1v1.333a3.667 3.667 0 0 0 3.412 3.658A5.009 5.009 0 0 0 7 11.9V13H6a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2H9v-1.1a5.009 5.009 0 0 0 3.588-2.909A3.667 3.667 0 0 0 16 5.333V4a1 1 0 0 0-1-1h-2V2a1 1 0 0 0-1-1H4Zm4 9a3 3 0 0 0 3-3V3H5v4a3 3 0 0 0 3 3Zm6-4.667c0 .684-.411 1.271-1 1.528V5h1v.333ZM3 6.861V5H2v.333c0 .684.411 1.271 1 1.528Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconTopRatedSeller16: EbayIconComponent = props => (
    <EbayIcon {...props} name="topRatedSeller16" __type="icon" __symbol={SYMBOL} />
);