/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-speedometer-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 9a6 6 0 1 1 10.2 4.286 1 1 0 1 0 1.399 1.428 8 8 0 1 0-11.198 0 1 1 0 1 0 1.4-1.428A5.979 5.979 0 0 1 2 9Zm7.75 0c0-.105-.01-.208-.027-.309l1.282-1.282a1 1 0 0 0-1.414-1.414L8.309 7.277A1.75 1.75 0 1 0 9.75 9Z"/></symbol>`;

export const EbayIconSpeedometer16: EbayIconComponent = props => (
    <EbayIcon {...props} name="speedometer16" __type="icon" __symbol={SYMBOL} />
);