/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-external-link-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 2a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 1 1-2 0V4.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L15.586 3H13a1 1 0 0 1-1-1ZM5 3a3 3 0 0 0-3 3v9a3 3 0 0 0 3 3h9a3 3 0 0 0 3-3v-4a1 1 0 1 0-2 0v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h4a1 1 0 0 0 0-2H5Z"/></symbol>`;

export const EbayIconExternalLink20: EbayIconComponent = props => (
    <EbayIcon {...props} name="externalLink20" __type="icon" __symbol={SYMBOL} />
);