/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-profile-verification-24"><path d="M12 12a8.979 8.979 0 0 1 4.5 1.205 1 1 0 0 1-1.001 1.73A6.961 6.961 0 0 0 12 14a7 7 0 0 0-6.928 6H11a1 1 0 0 1 0 2H5c-1.067 0-2.084-.893-1.931-2.121l.061-.414C3.86 15.225 7.552 12 12 12Zm8.293 4.293a1 1 0 0 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 1 1 1.414-1.414L17 19.586l3.293-3.293ZM12 1a5 5 0 1 1-.001 10 5 5 0 0 1 0-10Zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></symbol>`;

export const EbayIconProfileVerification24: EbayIconComponent = props => (
    <EbayIcon {...props} name="profileVerification24" __type="icon" __symbol={SYMBOL} />
);