/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-rupee-24"><path d="M6 3a1 1 0 0 1 1-1h11a1 1 0 1 1 0 2h-4.537c.763.753 1.288 1.744 1.468 3H18a1 1 0 1 1 0 2h-3.069c-.255 1.777-1.2 3.027-2.54 3.82-1.053.624-2.311.944-3.585 1.086l5.026 7.54a1 1 0 0 1-1.664 1.109L6.272 13.71c-.49-.735.04-1.702.905-1.71 2.173-.023 5.177-.464 5.724-3H7a1 1 0 0 1 0-2h5.901C12.341 4.4 9.211 4 7 4a1 1 0 0 1-1-1Z"/></symbol>`;

export const EbayIconRupee24: EbayIconComponent = props => (
    <EbayIcon {...props} name="rupee24" __type="icon" __symbol={SYMBOL} />
);