/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-arrow-left-20"><path d="M10.707 2.293a1 1 0 0 1 0 1.414L5.414 9H17a1 1 0 1 1 0 2H5.414l5.293 5.293a1 1 0 0 1-1.414 1.414l-7-7a1 1 0 0 1 0-1.414l7-7a1 1 0 0 1 1.414 0Z"/></symbol>`;

export const EbayIconArrowLeft20: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowLeft20" __type="icon" __symbol={SYMBOL} />
);