/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-play-20"><path d="m6.142 2.205 11.2 6.665a1.3 1.3 0 0 1 0 2.26l-11.2 6.665C5.21 18.35 4 17.712 4 16.665V3.335c0-1.047 1.21-1.685 2.142-1.13Z"/></symbol>`;

export const EbayIconPlay20: EbayIconComponent = props => (
    <EbayIcon {...props} name="play20" __type="icon" __symbol={SYMBOL} />
);