/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-return-16"><path d="M6.707 2.707a1 1 0 0 0-1.414-1.414l-3 3a.997.997 0 0 0 0 1.414l3 3a1 1 0 1 0 1.414-1.414L5.414 6H9c2.31 0 4 1.663 4 3.5 0 1.836-1.69 3.5-4 3.5H4a1 1 0 1 0 0 2h5c3.212 0 6-2.366 6-5.5S12.212 4 9 4H5.414l1.293-1.293Z"/></symbol>`;

export const EbayIconReturn16: EbayIconComponent = props => (
    <EbayIcon {...props} name="return16" __type="icon" __symbol={SYMBOL} />
);