/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-download-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 2a1 1 0 1 0-2 0v9.586L5.707 8.293a1 1 0 0 0-1.414 1.414l5 5a1 1 0 0 0 1.414 0l5-5a1 1 0 0 0-1.414-1.414L11 11.586V2ZM2 17a1 1 0 1 0 0 2h16a1 1 0 1 0 0-2H2Z"/></symbol>`;

export const EbayIconDownload20: EbayIconComponent = props => (
    <EbayIcon {...props} name="download20" __type="icon" __symbol={SYMBOL} />
);