/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-search-20"><path fill-rule="evenodd" d="M13.05 14.463a7.5 7.5 0 1 1 1.414-1.414l4.243 4.244a1 1 0 0 1-1.414 1.414l-4.244-4.244ZM14 8.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconSearch20: EbayIconComponent = props => (
    <EbayIcon {...props} name="search20" __type="icon" __symbol={SYMBOL} />
);