/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-mail-24"><path fill-rule="evenodd" d="M4 3a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h16a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3H4Zm17 3.5V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v.5l8.4 6.3a1 1 0 0 0 1.2 0L21 6.5ZM3 9v9a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9l-7.2 5.4a3 3 0 0 1-3.6 0L3 9Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconMail24: EbayIconComponent = props => (
    <EbayIcon {...props} name="mail24" __type="icon" __symbol={SYMBOL} />
);