/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-truck-shipped-12"><path d="M6.3 1a1.95 1.95 0 0 1 1.95 1.95v.8h1.14a1.5 1.5 0 0 1 1.17.563L11.67 5.7c.214.266.33.597.33.938V8a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-3 0H4a1.5 1.5 0 0 1-3 0H.75a.75.75 0 0 1 0-1.5H6.3a.45.45 0 0 0 .45-.45v-4.6a.45.45 0 0 0-.45-.45H.75a.75.75 0 0 1 0-1.5H6.3Zm1.95 6.55c0 .155-.02.305-.055.45H10.5V6.638L9.39 5.25H8.25v2.3ZM3.75 4.5a.75.75 0 0 1 0 1.5h-3a.75.75 0 0 1 0-1.5h3Z"/></symbol>`;

export const EbayIconTruckShipped12: EbayIconComponent = props => (
    <EbayIcon {...props} name="truckShipped12" __type="icon" __symbol={SYMBOL} />
);