/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-live-eye-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.808 6.844a10.135 10.135 0 0 0-1.913 2.603 1 1 0 0 1-1.79-.894 12.129 12.129 0 0 1 2.312-3.147C3.697 4.17 5.557 3 8 3s4.304 1.169 5.583 2.406a12.128 12.128 0 0 1 2.312 3.147 1 1 0 1 1-1.79.894 10.136 10.136 0 0 0-1.913-2.603C11.146 5.83 9.757 5 8 5c-1.757 0-3.146.831-4.192 1.844ZM8 12.25a2.25 2.25 0 1 0 0-4.5 2.25 2.25 0 0 0 0 4.5Z"/></symbol>`;

export const EbayIconLiveEye16: EbayIconComponent = props => (
    <EbayIcon {...props} name="liveEye16" __type="icon" __symbol={SYMBOL} />
);