/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-density-row-compact-16"><path d="M13.5 1A2.5 2.5 0 0 1 16 3.5v9a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 0 12.5v-9A2.5 2.5 0 0 1 2.5 1h11Zm-11 2a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-11Zm8.5 7a1 1 0 1 1 0 2H5a1 1 0 1 1 0-2h6Zm0-3a1 1 0 1 1 0 2H5a1 1 0 0 1 0-2h6Zm0-3a1 1 0 1 1 0 2H5a1 1 0 0 1 0-2h6Z"/></symbol>`;

export const EbayIconDensityRowCompact16: EbayIconComponent = props => (
    <EbayIcon {...props} name="densityRowCompact16" __type="icon" __symbol={SYMBOL} />
);