/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-panel-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 5a1 1 0 0 1 1-1h3v12H3a1 1 0 0 1-1-1V5Zm6 11h9a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H8v12ZM3 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h14a3 3 0 0 0 3-3V5a3 3 0 0 0-3-3H3Z"/></symbol>`;

export const EbayIconPanel20: EbayIconComponent = props => (
    <EbayIcon {...props} name="panel20" __type="icon" __symbol={SYMBOL} />
);