/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-panel-open-vertical-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M15 0a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3h10Zm1 3a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v2h12V3ZM4 17V7h12v10a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1Zm5.271-1.315L7.21 13.624a1 1 0 1 1 1.414-1.414l.376.375V10a1 1 0 1 1 2 0v2.585l.376-.375a1 1 0 1 1 1.414 1.414l-2.061 2.061a.994.994 0 0 1-.67.313.998.998 0 0 1-.766-.29l-.022-.023Z"/></symbol>`;

export const EbayIconPanelOpenVertical20: EbayIconComponent = props => (
    <EbayIcon {...props} name="panelOpenVertical20" __type="icon" __symbol={SYMBOL} />
);