/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-print-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 .5.5V4H5V2.5ZM3 4V2.5A2.5 2.5 0 0 1 5.5 0h5A2.5 2.5 0 0 1 13 2.5V4h.5A2.5 2.5 0 0 1 16 6.5v4a2.5 2.5 0 0 1-2.5 2.5H13v.5a2.5 2.5 0 0 1-2.5 2.5h-5A2.5 2.5 0 0 1 3 13.5V13h-.5A2.5 2.5 0 0 1 0 10.5v-4A2.5 2.5 0 0 1 2.5 4H3Zm0 7V9a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2h.5a.5.5 0 0 0 .5-.5v-4a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 .5.5H3Zm2 2.5a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 .5-.5V10H5v3.5Z"/></symbol>`;

export const EbayIconPrint16: EbayIconComponent = props => (
    <EbayIcon {...props} name="print16" __type="icon" __symbol={SYMBOL} />
);