/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-chevron-up-20"><path d="M9.293 4.293a.999.999 0 0 1 1.414 0l7 7a1 1 0 0 1-1.414 1.414L10 6.414l-6.293 6.293a1 1 0 0 1-1.414-1.414l7-7Z"/></symbol>`;

export const EbayIconChevronUp20: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronUp20" __type="icon" __symbol={SYMBOL} />
);