/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-confirmation-filled-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm11.207-.793a1 1 0 0 0-1.414-1.414L7 8.586l-.793-.793a1 1 0 0 0-1.414 1.414l1.5 1.5a1 1 0 0 0 1.414 0l3.5-3.5Z"/></symbol>`;

export const EbayIconConfirmationFilled16: EbayIconComponent = props => (
    <EbayIcon {...props} name="confirmationFilled16" __type="icon" __symbol={SYMBOL} />
);