/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chair-24"><path fill-rule="evenodd" d="M4 4a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v7.126c1.725.444 3 2.01 3 3.874v7a1 1 0 1 1-2 0v-4H3v4a1 1 0 1 1-2 0v-7a4.002 4.002 0 0 1 3-3.874V4ZM3 16h18v-1a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v1ZM18 4v7H6V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconChair24: EbayIconComponent = props => (
    <EbayIcon {...props} name="chair24" __type="icon" __symbol={SYMBOL} />
);