/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-cart-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.236 4H1a1 1 0 1 1 0-2h1.97c.458-.014.884.296 1 .755L4.855 6H17c.654 0 1.141.646.962 1.274l-1.586 5.55A3 3 0 0 1 13.491 15H7.528a3 3 0 0 1-2.895-2.21L2.236 4Zm4.327 8.263L5.4 8h10.274l-1.221 4.274a1 1 0 0 1-.962.726H7.528a1 1 0 0 1-.965-.737Z"/><path d="M8 18.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm6.5 1.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"/></symbol>`;

export const EbayIconCart20: EbayIconComponent = props => (
    <EbayIcon {...props} name="cart20" __type="icon" __symbol={SYMBOL} />
);