/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-download-16"><path d="M8 1a1 1 0 0 1 1 1v5.586l2.293-2.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-4-4a1 1 0 0 1 1.414-1.414L7 7.586V2a1 1 0 0 1 1-1Z"/><path fill-rule="evenodd" d="M1 14a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H2a1 1 0 0 1-1-1Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconDownload16: EbayIconComponent = props => (
    <EbayIcon {...props} name="download16" __type="icon" __symbol={SYMBOL} />
);