/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-full-view-filled-24"><path d="M2 3h20a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Zm20 16H2a1 1 0 0 0 0 2h20a1 1 0 0 0 0-2Z"/></symbol>`;

export const EbayIconFullViewFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="fullViewFilled24" __type="icon" __symbol={SYMBOL} />
);