/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-bookmark-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 3a1 1 0 0 0-1 1v15.586l5.293-5.293a1 1 0 0 1 1.414 0L18 19.586V4a1 1 0 0 0-1-1H7ZM4 4a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v18a1 1 0 0 1-1.707.707L12 16.414l-6.293 6.293A1 1 0 0 1 4 22V4Z"/></symbol>`;

export const EbayIconBookmark24: EbayIconComponent = props => (
    <EbayIcon {...props} name="bookmark24" __type="icon" __symbol={SYMBOL} />
);