/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-add-16"><path d="M14 7H9V2a1 1 0 0 0-2 0v5H2a1 1 0 0 0 0 2h5v5a1 1 0 1 0 2 0V9h5a1 1 0 1 0 0-2Z"/></symbol>`;

export const EbayIconAdd16: EbayIconComponent = props => (
    <EbayIcon {...props} name="add16" __type="icon" __symbol={SYMBOL} />
);