/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-panel-close-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 4a2.5 2.5 0 0 1 2.5-2.5h11A2.5 2.5 0 0 1 16 4v8a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 0 12V4Zm2.5-.5A.5.5 0 0 0 2 4v8a.5.5 0 0 0 .5.5H10v-9H2.5Zm11 9H12v-9h1.5a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5ZM6.32 6.738l-.44.512h1.87a.75.75 0 0 1 0 1.5H5.88l.44.512a.75.75 0 0 1-1.14.976l-1.5-1.75a.747.747 0 0 1 .01-.988l1.49-1.738a.75.75 0 0 1 1.14.976Z"/></symbol>`;

export const EbayIconPanelClose16: EbayIconComponent = props => (
    <EbayIcon {...props} name="panelClose16" __type="icon" __symbol={SYMBOL} />
);