/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-arrow-up-20"><path d="M2.293 10.707a1 1 0 0 0 1.414 0L9 5.414V17a1 1 0 1 0 2 0V5.414l5.293 5.293a1 1 0 0 0 1.414-1.414l-7-7a1 1 0 0 0-1.414 0l-7 7a1 1 0 0 0 0 1.414Z"/></symbol>`;

export const EbayIconArrowUp20: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowUp20" __type="icon" __symbol={SYMBOL} />
);