/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-return-24"><path d="M9.707 3.707a1 1 0 0 0-1.414-1.414l-5 5a.999.999 0 0 0 0 1.414l5 5a1 1 0 0 0 1.414-1.414L6.414 9H14c3.385 0 6 2.53 6 5.5S17.385 20 14 20H5a1 1 0 1 0 0 2h9c4.347 0 8-3.29 8-7.5S18.347 7 14 7H6.414l3.293-3.293Z"/></symbol>`;

export const EbayIconReturn24: EbayIconComponent = props => (
    <EbayIcon {...props} name="return24" __type="icon" __symbol={SYMBOL} />
);