/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-sort-down-12"><path d="m6.523 10.789 4.27-4.287a.717.717 0 0 0-.003-1.011.71.71 0 0 0-1.007.003L6.729 8.567V1.715A.713.713 0 0 0 6.017 1a.713.713 0 0 0-.711.715v6.852L2.252 5.494a.71.71 0 0 0-1.232.298.716.716 0 0 0 .229.71l4.27 4.287a.71.71 0 0 0 1.004 0Z"/></symbol>`;

export const EbayIconSortDown12: EbayIconComponent = props => (
    <EbayIcon {...props} name="sortDown12" __type="icon" __symbol={SYMBOL} />
);