/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-package-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.9 2.8A2 2 0 0 1 5.5 2h13a2 2 0 0 1 1.6.8l2.3 3.067a3 3 0 0 1 .6 1.8V19a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V7.667a3 3 0 0 1 .6-1.8L3.9 2.8ZM18.5 4H13v2h7l-1.5-2ZM21 8h-8v12h7a1 1 0 0 0 1-1V8ZM11 6V4H5.5L4 6h7ZM3 8v11a1 1 0 0 0 1 1h7V8H3Z"/></symbol>`;

export const EbayIconPackage24: EbayIconComponent = props => (
    <EbayIcon {...props} name="package24" __type="icon" __symbol={SYMBOL} />
);