/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-remove-24"><path d="M21 11H3a1 1 0 0 0 0 2h18a1 1 0 0 0 0-2Z"/></symbol>`;

export const EbayIconRemove24: EbayIconComponent = props => (
    <EbayIcon {...props} name="remove24" __type="icon" __symbol={SYMBOL} />
);