/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-moon-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.222 1.413a1 1 0 0 1 .112.986 4.01 4.01 0 0 0 5.267 5.269 1 1 0 0 1 1.39 1.017 7.013 7.013 0 1 1-7.674-7.676 1 1 0 0 1 .905.404ZM6.041 3.377A5.015 5.015 0 0 0 8.013 13a5.015 5.015 0 0 0 4.609-3.04 6.01 6.01 0 0 1-6.581-6.583Z"/></symbol>`;

export const EbayIconMoon16: EbayIconComponent = props => (
    <EbayIcon {...props} name="moon16" __type="icon" __symbol={SYMBOL} />
);