/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-home-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M14.684 2.03a4 4 0 0 0-5.368 0l-7.33 6.634A3 3 0 0 0 1 10.888v9.863A2.25 2.25 0 0 0 3.25 23h4.5A2.25 2.25 0 0 0 10 20.75V15.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v5.25A2.25 2.25 0 0 0 16.25 23h4.5A2.25 2.25 0 0 0 23 20.75v-9.863a3 3 0 0 0-.987-2.224L14.684 2.03Z"/></symbol>`;

export const EbayIconHomeFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="homeFilled24" __type="icon" __symbol={SYMBOL} />
);