/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-text-size-16"><path d="M9 3a1 1 0 0 1 0 2H6.504L6.5 13.001l-.005.101a1 1 0 0 1-1.99 0l-.005-.103L4.504 5H2a1 1 0 0 1 0-2h7Zm5.102 4.005a1 1 0 0 1 0 1.99L14 9h-1.5v4a1 1 0 1 1-2 0V9H9a1 1 0 0 1 0-2h5l.102.005Z"/></symbol>`;

export const EbayIconTextSize16: EbayIconComponent = props => (
    <EbayIcon {...props} name="textSize16" __type="icon" __symbol={SYMBOL} />
);