/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-density-default-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 5.75A1.5 1.5 0 0 0 1 7.25v2a1.5 1.5 0 0 0 1.5 1.5h2A1.5 1.5 0 0 0 6 9.25v-2a1.5 1.5 0 0 0-1.5-1.5h-2Zm0 7.5a1.5 1.5 0 0 0-1.5 1.5v2a1.5 1.5 0 0 0 1.5 1.5h2a1.5 1.5 0 0 0 1.5-1.5v-2a1.5 1.5 0 0 0-1.5-1.5h-2Zm6.5-5a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H10a1 1 0 0 1-1-1Zm1 6.5a1 1 0 1 0 0 2h12a1 1 0 1 0 0-2H10Z"/></symbol>`;

export const EbayIconDensityDefault24: EbayIconComponent = props => (
    <EbayIcon {...props} name="densityDefault24" __type="icon" __symbol={SYMBOL} />
);