/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-flag-filled-24"><path d="M20.953 1.695A.999.999 0 0 0 19.987 1H6a1 1 0 0 0-1 1v20a1 1 0 1 0 2 0v-9h12.979c.036 0 .072 0 .107-.004a1 1 0 0 0 .466-1.83L14.72 7l5.85-4.178a1.007 1.007 0 0 0 .428-.761 1 1 0 0 0-.045-.366Z"/></symbol>`;

export const EbayIconFlagFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="flagFilled24" __type="icon" __symbol={SYMBOL} />
);