/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-mobile-20"><path d="M13 1a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h6ZM7 3a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H7Zm3.75 11a1 1 0 1 1 0 2h-1.5a1 1 0 1 1 0-2h1.5Z"/></symbol>`;

export const EbayIconMobile20: EbayIconComponent = props => (
    <EbayIcon {...props} name="mobile20" __type="icon" __symbol={SYMBOL} />
);