/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-confirmation-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12c0-3.183-1.264-6.235-3.515-8.485A11.996 11.996 0 0 0 12 0Zm4.715 10.035A1 1 0 0 0 15.3 8.621l-4.632 4.631-1.962-1.962a1 1 0 0 0-1.414 1.415l2.67 2.669a1 1 0 0 0 1.413 0l5.339-5.339Z"/></symbol>`;

export const EbayIconConfirmationFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="confirmationFilled24" __type="icon" __symbol={SYMBOL} />
);