/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 5 6" id="icon-eek-range-arrow"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.32203 0.108736L1.0202 2.6473C0.951945 2.78038 1.04859 2.93856 1.19816 2.93856H1.95692V5.99786H3.04303V2.93856H3.80182C3.95139 2.93856 4.04804 2.78038 3.97979 2.6473L2.67796 0.108736C2.60361 -0.0362453 2.39638 -0.0362455 2.32203 0.108736Z" fill="black"/></symbol>`;

export const EbayIconEekRangeArrow: EbayIconComponent = props => (
    <EbayIcon {...props} name="eekRangeArrow" __type="icon" __symbol={SYMBOL} />
);