/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-feedback-negative-16"><path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0ZM5 7a1 1 0 0 0 0 2h6a1 1 0 1 0 0-2H5Z"/></symbol>`;

export const EbayIconFeedbackNegative16: EbayIconComponent = props => (
    <EbayIcon {...props} name="feedbackNegative16" __type="icon" __symbol={SYMBOL} />
);