/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 50 32" id="icon-general-card-32-colored"><rect x=".5" y=".5" width="49" height="31" rx="1.5" fill="#fff" stroke="#000" stroke-width="1"/><rect x="38.5" y="24.5" width="6" height="1" rx=".5" fill="#A2A2A2" stroke="#A2A2A2"/><rect x="27.5" y="24.5" width="6" height="1" rx=".5" fill="#A2A2A2" stroke="#A2A2A2"/><rect x="16.5" y="24.5" width="6" height="1" rx=".5" fill="#A2A2A2" stroke="#A2A2A2"/><rect x="5.5" y="24.5" width="6" height="1" rx=".5" fill="#A2A2A2" stroke="#A2A2A2"/><rect x="5.9" y="9.9" width="9.2" height="5.2" rx=".9" fill="#A2A2A2" stroke="#A2A2A2" stroke-width="1.8"/></symbol>`;

export const EbayIconGeneralCard32Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="generalCard32Colored" __type="icon" __symbol={SYMBOL} />
);