/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-confirmation-filled-12"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 6a6 6 0 1 1 12 0A6 6 0 0 1 0 6Zm8.757-.94a.825.825 0 0 0-1.168-1.166L5.132 6.356l-.722-.721a.825.825 0 0 0-1.166 1.167L4.55 8.107a.825.825 0 0 0 1.167 0l3.04-3.048Z"/></symbol>`;

export const EbayIconConfirmationFilled12: EbayIconComponent = props => (
    <EbayIcon {...props} name="confirmationFilled12" __type="icon" __symbol={SYMBOL} />
);