/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-refresh-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M10 4a6 6 0 1 0 5.423 8.57 1 1 0 0 1 1.807.86A8 8 0 1 1 10 2a8.113 8.113 0 0 1 6 2.653V3a1 1 0 1 1 2 0v4a1 1 0 0 1-1.017 1H13a1 1 0 1 1 0-2h1.521A6.114 6.114 0 0 0 10 4Z"/></symbol>`;

export const EbayIconRefresh20: EbayIconComponent = props => (
    <EbayIcon {...props} name="refresh20" __type="icon" __symbol={SYMBOL} />
);