/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 64 64" id="icon-graph-64"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 7.501a2.5 2.5 0 1 0-5 0v43a7.5 7.5 0 0 0 7.5 7.5h48a2.5 2.5 0 0 0 0-5h-48a2.5 2.5 0 0 1-2.5-2.5v-43Zm6.619 33.354 13.974-15.97a2.5 2.5 0 0 1 3.696-.13l6.135 6.134 15.235-16.58a2.5 2.5 0 1 1 3.682 3.384l-17 18.5a2.5 2.5 0 0 1-3.636.048l-6.083-6.083-12.24 13.99a2.5 2.5 0 1 1-3.763-3.293Z"/></symbol>`;

export const EbayIconGraph64: EbayIconComponent = props => (
    <EbayIcon {...props} name="graph64" __type="icon" __symbol={SYMBOL} />
);