/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-sort-up-12"><path d="m5.477 1.21-4.27 4.288A.717.717 0 0 0 1.21 6.51a.71.71 0 0 0 1.007-.003l3.054-3.073v6.852a.713.713 0 1 0 1.423 0V3.433l3.054 3.073a.71.71 0 0 0 1.232-.298.716.716 0 0 0-.229-.71l-4.27-4.287a.71.71 0 0 0-1.004 0Z"/></symbol>`;

export const EbayIconSortUp12: EbayIconComponent = props => (
    <EbayIcon {...props} name="sortUp12" __type="icon" __symbol={SYMBOL} />
);