/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-arrow-left-24"><path d="M21 11H5.41l6.3-6.29a1.003 1.003 0 1 0-1.42-1.42l-8 8a1.001 1.001 0 0 0 0 1.42l8 8a1.001 1.001 0 0 0 1.42 0 1.001 1.001 0 0 0 0-1.42L5.41 13H21a1 1 0 0 0 0-2Z"/></symbol>`;

export const EbayIconArrowLeft24: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowLeft24" __type="icon" __symbol={SYMBOL} />
);