/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-sparkline-up-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M16.25 6a1.25 1.25 0 1 0 0 2.5h2.482L13 14.232l-4.116-4.116a1.25 1.25 0 0 0-1.768 0l-5.75 5.75a1.25 1.25 0 0 0 1.768 1.768L8 12.768l4.116 4.116a1.25 1.25 0 0 0 1.768 0l6.616-6.616v2.482a1.25 1.25 0 1 0 2.5 0v-5.5C23 6.56 22.44 6 21.75 6h-5.5Z"/></symbol>`;

export const EbayIconSparklineUpFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineUpFilled24" __type="icon" __symbol={SYMBOL} />
);