/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-pause-16"><path d="M4.5 2A1.5 1.5 0 0 0 3 3.5v9a1.5 1.5 0 0 0 3 0v-9A1.5 1.5 0 0 0 4.5 2Zm7 0A1.5 1.5 0 0 0 10 3.5v9a1.5 1.5 0 0 0 3 0v-9A1.5 1.5 0 0 0 11.5 2Z"/></symbol>`;

export const EbayIconPause16: EbayIconComponent = props => (
    <EbayIcon {...props} name="pause16" __type="icon" __symbol={SYMBOL} />
);