/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-sparkline-down-16"><path d="M10 12a1 1 0 1 1 0-2h1.586L9 7.414 6.707 9.707a1 1 0 0 1-1.414 0l-4-4a1 1 0 0 1 1.414-1.414L6 7.586l2.293-2.293a1 1 0 0 1 1.414 0L13 8.586V7a1 1 0 1 1 2 0v4a1 1 0 0 1-1 1h-4Z"/></symbol>`;

export const EbayIconSparklineDown16: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineDown16" __type="icon" __symbol={SYMBOL} />
);