/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-mobile-24"><path d="M16.154 1.004A3 3 0 0 1 19 4v16a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h8l.154.004ZM8 3a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-.898-.995L16 3H8Zm5 15a1 1 0 1 1 0 2h-2a1 1 0 1 1 0-2h2Z"/></symbol>`;

export const EbayIconMobile24: EbayIconComponent = props => (
    <EbayIcon {...props} name="mobile24" __type="icon" __symbol={SYMBOL} />
);