/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-customize-24"><path d="M18 13a4 4 0 1 1-3.876 4.991c-.04.005-.082.009-.124.009H3a1 1 0 1 1 0-2h11c.042 0 .083.003.124.008A4.002 4.002 0 0 1 18 13Zm0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4ZM6 3a4 4 0 0 1 3.875 3.008C9.916 6.003 9.958 6 10 6h11a1 1 0 1 1 0 2H10c-.042 0-.084-.004-.125-.009A4 4 0 1 1 6 3Zm0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/></symbol>`;

export const EbayIconCustomize24: EbayIconComponent = props => (
    <EbayIcon {...props} name="customize24" __type="icon" __symbol={SYMBOL} />
);