/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-arrow-right-20"><path d="M9.293 2.293a1 1 0 0 0 0 1.414L14.586 9H3a1 1 0 1 0 0 2h11.586l-5.293 5.293a1 1 0 1 0 1.414 1.414l7-7a1 1 0 0 0 0-1.414l-7-7a1 1 0 0 0-1.414 0Z"/></symbol>`;

export const EbayIconArrowRight20: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowRight20" __type="icon" __symbol={SYMBOL} />
);