/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-note-24"><path d="M18 1a3 3 0 0 1 3 3v16a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h12ZM6 3a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H6Zm6 11a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h4Zm4-4a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h8Zm0-4a1 1 0 1 1 0 2H8a1 1 0 0 1 0-2h8Z"/></symbol>`;

export const EbayIconNote24: EbayIconComponent = props => (
    <EbayIcon {...props} name="note24" __type="icon" __symbol={SYMBOL} />
);