/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-chevron-up-16"><path d="m8.707 3.293 6 6a1 1 0 0 1-1.414 1.414L8 5.414l-5.293 5.293a1 1 0 0 1-1.414-1.414l6-6a1 1 0 0 1 1.414 0Z"/></symbol>`;

export const EbayIconChevronUp16: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronUp16" __type="icon" __symbol={SYMBOL} />
);