/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 18 18" id="icon-radio-unchecked-18"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 18A9 9 0 1 1 9 0a9 9 0 0 1 0 18ZM9 1a8 8 0 1 0 0 16A8 8 0 0 0 9 1Z"/></symbol>`;

export const EbayIconRadioUnchecked18: EbayIconComponent = props => (
    <EbayIcon {...props} name="radioUnchecked18" __type="icon" __symbol={SYMBOL} />
);