/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-chevron-right-16"><path d="m12.707 8.707-6 6a1 1 0 0 1-1.414-1.414L10.586 8 5.293 2.707a1 1 0 0 1 1.414-1.414l6 6a1 1 0 0 1 0 1.414Z"/></symbol>`;

export const EbayIconChevronRight16: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronRight16" __type="icon" __symbol={SYMBOL} />
);