/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-arrow-up-12"><path d="m5.477 1.208-4.27 4.287a.717.717 0 0 0 .003 1.01.71.71 0 0 0 1.007-.003L5.271 3.43v6.852a.713.713 0 1 0 1.423 0V3.43l3.054 3.072a.71.71 0 0 0 1.232-.297.716.716 0 0 0-.229-.71l-4.27-4.287a.71.71 0 0 0-1.004 0Z"/></symbol>`;

export const EbayIconArrowUp12: EbayIconComponent = props => (
    <EbayIcon {...props} name="arrowUp12" __type="icon" __symbol={SYMBOL} />
);