/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-yuan-16"><path d="M1.35.24a1 1 0 0 1 1.41.11L8 6.462 13.24.35a1 1 0 1 1 1.52 1.302L9.316 8H12a1 1 0 1 1 0 2H9v1h3a1 1 0 1 1 0 2H9v2a1 1 0 1 1-2 0v-2H4a1 1 0 1 1 0-2h3v-1H4a1 1 0 1 1 0-2h2.683L1.24 1.65A1 1 0 0 1 1.349.24Z"/></symbol>`;

export const EbayIconYuan16: EbayIconComponent = props => (
    <EbayIcon {...props} name="yuan16" __type="icon" __symbol={SYMBOL} />
);