/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-profile-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 8a6 6 0 1 1 10.472 4A5.986 5.986 0 0 0 8 10a5.986 5.986 0 0 0-4.472 2A5.978 5.978 0 0 1 2 8Zm6-8a8 8 0 1 0 0 16A8 8 0 0 0 8 0Zm2.375 6.625a2.375 2.375 0 1 1-4.75 0 2.375 2.375 0 0 1 4.75 0Z"/></symbol>`;

export const EbayIconProfile16: EbayIconComponent = props => (
    <EbayIcon {...props} name="profile16" __type="icon" __symbol={SYMBOL} />
);