/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 38 24" id="icon-bank-account-24-colored"><rect x=".5" y=".5" width="37" height="23" rx="1.5" fill="#fff" stroke="#000" stroke-width="1"/><path d="m19.001 4.08-7.508 4.736a.703.703 0 0 0 .375 1.298h14.283a.703.703 0 0 0 .375-1.298L19.001 4.08Zm-4.7 4.628 4.701-2.966 4.712 2.966h-9.413Zm-.458 8.297V11.66h1.406v5.344h-1.406Zm2.976-5.344v5.344h1.406V11.66h-1.406Zm2.975 0v5.344h1.407V11.66h-1.407Zm2.976 0v5.344h1.406V11.66H22.77Zm-11.605 7.567c0-.388.315-.703.703-.703h14.283a.703.703 0 1 1 0 1.406H11.868a.703.703 0 0 1-.703-.703Z" fill="#000"/></symbol>`;

export const EbayIconBankAccount24Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="bankAccount24Colored" __type="icon" __symbol={SYMBOL} />
);