/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-bar-chart-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 21a1 1 0 1 0 2 0V8a1 1 0 1 0-2 0v13Zm5.333 0a1 1 0 1 0 2 0v-9a1 1 0 1 0-2 0v9ZM20 22a1 1 0 0 1-1-1V8a1 1 0 1 1 2 0v13a1 1 0 0 1-1 1Zm-6.334-1a1 1 0 1 0 2 0V2a1 1 0 1 0-2 0v19Z"/></symbol>`;

export const EbayIconBarChart24: EbayIconComponent = props => (
    <EbayIcon {...props} name="barChart24" __type="icon" __symbol={SYMBOL} />
);