/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-authenticity-guarantee-filled-24-colored"><path d="M2.067 6.647a3.756 3.756 0 0 1-.875 2.113A4.98 4.98 0 0 0 0 12a4.98 4.98 0 0 0 1.191 3.24 3.75 3.75 0 0 1 .876 2.113 4.98 4.98 0 0 0 1.448 3.132 4.98 4.98 0 0 0 3.133 1.449c.77.061 1.524.374 2.113.875A4.98 4.98 0 0 0 12 24a4.98 4.98 0 0 0 3.24-1.191 3.756 3.756 0 0 1 2.113-.875 4.98 4.98 0 0 0 3.133-1.449 4.98 4.98 0 0 0 1.448-3.133 3.76 3.76 0 0 1 .875-2.113A4.98 4.98 0 0 0 24 12a4.98 4.98 0 0 0-1.19-3.239 3.756 3.756 0 0 1-.876-2.113 4.98 4.98 0 0 0-1.448-3.133 4.98 4.98 0 0 0-3.133-1.449 3.756 3.756 0 0 1-2.114-.875A4.98 4.98 0 0 0 12 0a4.98 4.98 0 0 0-3.24 1.191 3.756 3.756 0 0 1-2.112.875 4.98 4.98 0 0 0-3.133 1.449 4.98 4.98 0 0 0-1.448 3.132Z" fill="#0968F6"/><path fill-rule="evenodd" clip-rule="evenodd" d="M16.711 8.621a1 1 0 0 1 0 1.414l-5.338 5.339a1 1 0 0 1-1.415 0l-2.669-2.67a1 1 0 1 1 1.414-1.414l1.962 1.963 4.632-4.632a1 1 0 0 1 1.414 0Z" fill="#fff"/></symbol>`;

export const EbayIconAuthenticityGuaranteeFilled24Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="authenticityGuaranteeFilled24Colored" __type="icon" __symbol={SYMBOL} />
);