/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-key-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 12a3 3 0 1 1 6 0 3 3 0 0 1-6 0Zm3-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M14.326 9a7 7 0 1 0 0 6H17v2a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-7a1 1 0 0 0-1-1h-7.674ZM8 7a5 5 0 1 0 4.716 6.667 1 1 0 0 1 .966-.667H18a1 1 0 0 1 1 1v2h2v-5h-7.318a1 1 0 0 1-.966-.667A5.002 5.002 0 0 0 8 7Z"/></symbol>`;

export const EbayIconKey24: EbayIconComponent = props => (
    <EbayIcon {...props} name="key24" __type="icon" __symbol={SYMBOL} />
);