/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-credit-card-24"><path d="M20 4a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3h16ZM3 11v6a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-6H3Zm1-5a1 1 0 0 0-1 1v1h18V7a1 1 0 0 0-1-1H4Z"/></symbol>`;

export const EbayIconCreditCard24: EbayIconComponent = props => (
    <EbayIcon {...props} name="creditCard24" __type="icon" __symbol={SYMBOL} />
);