/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 13 16" id="icon-trend-down-16-fit"><path d="m10.862 5.503-3.516 6.003a1 1 0 0 1-1.728-.004L2.136 5.5A.998.998 0 0 1 3.001 4h6.998a.998.998 0 0 1 .863 1.503Z"/></symbol>`;

export const EbayIconTrendDown16Fit: EbayIconComponent = props => (
    <EbayIcon {...props} name="trendDown16Fit" __type="icon" __symbol={SYMBOL} />
);