/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-share-ios-16"><path d="M8.707.293a1 1 0 0 0-1.414 0l-2 2a1 1 0 0 0 1.414 1.414L7 3.414V9a1 1 0 1 0 2 0V3.414l.293.293a1 1 0 0 0 1.414-1.414l-2-2Z"/><path d="M4.5 5A2.5 2.5 0 0 0 2 7.5v5A2.5 2.5 0 0 0 4.5 15h7a2.5 2.5 0 0 0 2.5-2.5v-5A2.5 2.5 0 0 0 11.5 5H11a1 1 0 1 0 0 2h.5a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-5a.5.5 0 0 1 .5-.5H5a1 1 0 0 0 0-2h-.5Z"/></symbol>`;

export const EbayIconShareIos16: EbayIconComponent = props => (
    <EbayIcon {...props} name="shareIos16" __type="icon" __symbol={SYMBOL} />
);