/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-tablet-20"><path d="M15 1a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h10ZM5 3a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H5Zm6.5 11a1 1 0 1 1 0 2h-3a1 1 0 1 1 0-2h3Z"/></symbol>`;

export const EbayIconTablet20: EbayIconComponent = props => (
    <EbayIcon {...props} name="tablet20" __type="icon" __symbol={SYMBOL} />
);