/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-drag-drop-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.5 6a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Zm9 0a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5ZM10 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm6.5 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Zm-6.5 6a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm6.5 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/></symbol>`;

export const EbayIconDragDrop24: EbayIconComponent = props => (
    <EbayIcon {...props} name="dragDrop24" __type="icon" __symbol={SYMBOL} />
);