/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-mail-open-16"><path fill-rule="evenodd" d="M9.467 1.479a2.5 2.5 0 0 0-2.934 0L1.66 5.01A1.6 1.6 0 0 0 1 6.306v6.186a2.5 2.5 0 0 0 2.5 2.5h9a2.5 2.5 0 0 0 2.5-2.5V6.306a1.6 1.6 0 0 0-.66-1.296L9.466 1.48Zm-1.76 1.619a.5.5 0 0 1 .587 0L12.38 6.06 8.285 8.912a.5.5 0 0 1-.572 0L3.62 6.061l4.088-2.963ZM3 8.067v4.425a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V8.066l-3.572 2.488a2.5 2.5 0 0 1-2.858 0L3 8.067Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconMailOpen16: EbayIconComponent = props => (
    <EbayIcon {...props} name="mailOpen16" __type="icon" __symbol={SYMBOL} />
);