/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-archive-24"><path d="M9 10a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2H9Z"/><path fill-rule="evenodd" d="M1 3a2 2 0 0 1 2-2h18a2 2 0 0 1 2 2v3a2 2 0 0 1-1 1.732V20a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V7.732A2 2 0 0 1 1 6V3Zm3 5h16v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V8Zm17-5H3v3h18V3Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconArchive24: EbayIconComponent = props => (
    <EbayIcon {...props} name="archive24" __type="icon" __symbol={SYMBOL} />
);