/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-radio-unchecked-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12s12-5.373 12-12c0-6.628-5.373-12-12-12m0 1c6.066 0 11 4.935 11 11s-4.934 11-11 11S1 18.065 1 12 5.934 1 12 1"/></symbol>`;

export const EbayIconRadioUnchecked24: EbayIconComponent = props => (
    <EbayIcon {...props} name="radioUnchecked24" __type="icon" __symbol={SYMBOL} />
);