/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-density-relaxed-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 9.5A1.5 1.5 0 0 0 1 11v2a1.5 1.5 0 0 0 1.5 1.5h2A1.5 1.5 0 0 0 6 13v-2a1.5 1.5 0 0 0-1.5-1.5h-2ZM10 11a1 1 0 1 0 0 2h12a1 1 0 1 0 0-2H10Z"/></symbol>`;

export const EbayIconDensityRelaxed24: EbayIconComponent = props => (
    <EbayIcon {...props} name="densityRelaxed24" __type="icon" __symbol={SYMBOL} />
);