/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-credit-card-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 4.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5V5H2v-.5ZM0 6V4.5A2.5 2.5 0 0 1 2.5 2h11A2.5 2.5 0 0 1 16 4.5v7a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 0 11.5V6Zm14 1v4.5a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5V7h12Z"/></symbol>`;

export const EbayIconCreditCard16: EbayIconComponent = props => (
    <EbayIcon {...props} name="creditCard16" __type="icon" __symbol={SYMBOL} />
);