/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-lightning-bolt-filled-12"><path d="M5.368.343a.751.751 0 0 1 1.38.407v3h2.247c1.189 0 1.904 1.319 1.257 2.316l-3.626 5.592a.75.75 0 0 1-1.378-.408v-3H3.005c-1.188 0-1.905-1.318-1.258-2.315L5.367.343Z"/></symbol>`;

export const EbayIconLightningBoltFilled12: EbayIconComponent = props => (
    <EbayIcon {...props} name="lightningBoltFilled12" __type="icon" __symbol={SYMBOL} />
);