/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 13 16" id="icon-trend-up-16-fit"><path d="M10.862 10.497 7.346 4.494a1 1 0 0 0-1.728.004L2.136 10.5a.998.998 0 0 0 .865 1.5h6.998a.998.998 0 0 0 .863-1.503Z"/></symbol>`;

export const EbayIconTrendUp16Fit: EbayIconComponent = props => (
    <EbayIcon {...props} name="trendUp16Fit" __type="icon" __symbol={SYMBOL} />
);