/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-rotate-portrait-right-24"><path d="M13 0a1 1 0 1 0 0 2h1a5 5 0 0 1 5 5v.586l-1.293-1.293a1 1 0 1 0-1.414 1.414l3 3a1 1 0 0 0 1.414 0l3-3a1 1 0 0 0-1.414-1.414L21 7.586V7a7 7 0 0 0-7-7h-1Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M4 5a3 3 0 0 0-3 3v13a3 3 0 0 0 3 3h7a3 3 0 0 0 3-3V8a3 3 0 0 0-3-3H4ZM3 8a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V8Z"/></symbol>`;

export const EbayIconRotatePortraitRight24: EbayIconComponent = props => (
    <EbayIcon {...props} name="rotatePortraitRight24" __type="icon" __symbol={SYMBOL} />
);