/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-reply-16"><path d="M8 6a7 7 0 0 1 7 7 1 1 0 1 1-2 0 5 5 0 0 0-5-5H3.414l2.293 2.293a1 1 0 1 1-1.414 1.414l-4-4a1 1 0 0 1 0-1.414l4-4a1 1 0 0 1 1.414 1.414L3.414 6H8Z"/></symbol>`;

export const EbayIconReply16: EbayIconComponent = props => (
    <EbayIcon {...props} name="reply16" __type="icon" __symbol={SYMBOL} />
);