/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-pause-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.75 4.75a1.75 1.75 0 1 0-3.5 0v10.5a1.75 1.75 0 1 0 3.5 0V4.75Zm8 0a1.75 1.75 0 1 0-3.5 0v10.5a1.75 1.75 0 1 0 3.5 0V4.75Z"/></symbol>`;

export const EbayIconPause20: EbayIconComponent = props => (
    <EbayIcon {...props} name="pause20" __type="icon" __symbol={SYMBOL} />
);