/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-chevron-left-20"><path d="M4.293 10.707a.999.999 0 0 1 0-1.414l7-7a1 1 0 1 1 1.414 1.414L6.414 10l6.293 6.293a1 1 0 0 1-1.414 1.414l-7-7Z"/></symbol>`;

export const EbayIconChevronLeft20: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronLeft20" __type="icon" __symbol={SYMBOL} />
);