/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-tablet-16"><path d="M12 0a2.5 2.5 0 0 1 2.5 2.5v11A2.5 2.5 0 0 1 12 16H4a2.5 2.5 0 0 1-2.5-2.5v-11A2.5 2.5 0 0 1 4 0h8ZM4 2a.5.5 0 0 0-.5.5v11a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-11A.5.5 0 0 0 12 2H4Zm5 9.5A.75.75 0 0 1 9 13H7a.75.75 0 0 1 0-1.5h2Z"/></symbol>`;

export const EbayIconTablet16: EbayIconComponent = props => (
    <EbayIcon {...props} name="tablet16" __type="icon" __symbol={SYMBOL} />
);