/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chevron-down-24"><path d="M12.376 17.927a.997.997 0 0 0 .331-.22l8-8a1 1 0 0 0-1.414-1.414L12 15.586 4.707 8.293a1 1 0 0 0-1.414 1.414l8 8a1 1 0 0 0 1.083.22Z"/></symbol>`;

export const EbayIconChevronDown24: EbayIconComponent = props => (
    <EbayIcon {...props} name="chevronDown24" __type="icon" __symbol={SYMBOL} />
);