/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-mobile-24"><path d="M11 18h2a1 1 0 1 1 0 2h-2a1 1 0 1 1 0-2Z"/><path d="M16 1H8a3 3 0 0 0-3 3v16a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3ZM8 3h8a1 1 0 0 1 1 1H7a1 1 0 0 1 1-1ZM7 6h10v9H7V6Zm0 11h10v3a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1v-3Z"/></symbol>`;

export const EbayIconMobile24: EbayIconComponent = props => (
    <EbayIcon {...props} name="mobile24" __type="icon" __symbol={SYMBOL} />
);