/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-unselect-all-24"><path d="M6 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm4 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm13-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-5 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm-3-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-5 21a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm-3-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-5 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm13-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 11a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 7a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1-3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm21-5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1-3a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm-1-3a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM.3 2.299a1 1 0 0 1 1.407-.006l20 20a1 1 0 0 1-1.414 1.414l-1.363-1.362a.995.995 0 1 1-1.275-1.275L2.93 6.345A.995.995 0 1 1 1.655 5.07L.293 3.707a1 1 0 0 1 .006-1.408Z"/></symbol>`;

export const EbayIconUnselectAll24: EbayIconComponent = props => (
    <EbayIcon {...props} name="unselectAll24" __type="icon" __symbol={SYMBOL} />
);