/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 64 64" id="icon-attention-64"><path d="M32 17a2.5 2.5 0 0 1 2.5 2.5v15a2.5 2.5 0 0 1-5 0v-15A2.5 2.5 0 0 1 32 17Zm2.5 27.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Z"/><path fill-rule="evenodd" d="M62 32c0 16.569-13.431 30-30 30C15.431 62 2 48.569 2 32 2 15.431 15.431 2 32 2c16.569 0 30 13.431 30 30Zm-5 0c0 13.807-11.193 25-25 25S7 45.807 7 32 18.193 7 32 7s25 11.193 25 25Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconAttention64: EbayIconComponent = props => (
    <EbayIcon {...props} name="attention64" __type="icon" __symbol={SYMBOL} />
);