/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-remove-12"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 6a.75.75 0 0 1 .75-.75h8.5a.75.75 0 0 1 0 1.5h-8.5A.75.75 0 0 1 1 6Z"/></symbol>`;

export const EbayIconRemove12: EbayIconComponent = props => (
    <EbayIcon {...props} name="remove12" __type="icon" __symbol={SYMBOL} />
);