/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-note-16"><path d="M11.5 1A2.5 2.5 0 0 1 14 3.5v9a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 12.5v-9A2.5 2.5 0 0 1 4.5 1h7Zm-7 2a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-7Zm3.603 5.005a1 1 0 0 1 0 1.99L8 10H6a1 1 0 0 1 0-2h2l.103.005ZM10 5a1 1 0 1 1 0 2H6a1 1 0 0 1 0-2h4Z"/></symbol>`;

export const EbayIconNote16: EbayIconComponent = props => (
    <EbayIcon {...props} name="note16" __type="icon" __symbol={SYMBOL} />
);