/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-rotate-24"><path d="M16.7 3.69 15.39 5a9 9 0 1 1-7.14 15 1.016 1.016 0 1 1 1.5-1.37A7 7 0 1 0 15.44 7l1.26 1.28a1 1 0 0 1-1.41 1.41l-3-3a1 1 0 0 1 0-1.41l3-3a1 1 0 0 1 1.41 1.41Zm-4.99 6.6-5-5a1 1 0 0 0-1.41 0l-5 5a1 1 0 0 0 0 1.41l5 5a1 1 0 0 0 1.41 0l5-5a1 1 0 0 0 0-1.41ZM6 14.59 2.41 11 6 7.41 9.59 11 6 14.59Z"/></symbol>`;

export const EbayIconRotate24: EbayIconComponent = props => (
    <EbayIcon {...props} name="rotate24" __type="icon" __symbol={SYMBOL} />
);