/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-history-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 3a5 5 0 1 1-4.332 7.5 1 1 0 1 0-1.73 1A7 7 0 1 0 8 1c-2.051 0-3.69.859-5.001 2.255V2.5a1 1 0 1 0-2 0V6a1 1 0 0 0 1 1h.23a.98.98 0 0 0 .038 0H5a1 1 0 1 0 0-2h-.875C5.22 3.666 6.485 3 8 3Zm1 3a1 1 0 0 0-2 0v2.5a1 1 0 0 0 .293.707l1.5 1.5a1 1 0 0 0 1.414-1.414L9 8.086V6Z"/></symbol>`;

export const EbayIconHistory16: EbayIconComponent = props => (
    <EbayIcon {...props} name="history16" __type="icon" __symbol={SYMBOL} />
);