/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-notification-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M5 8a7 7 0 0 1 14 0v3.05a.5.5 0 0 0 .082.276l2.5 3.8C22.678 16.788 21.485 19 19.495 19H16a4 4 0 0 1-8 0H4.505c-1.99 0-3.182-2.212-2.088-3.874l2.5-3.8A.5.5 0 0 0 5 11.05V8Zm5 11h4a2 2 0 0 1-4 0Z"/></symbol>`;

export const EbayIconNotificationFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="notificationFilled24" __type="icon" __symbol={SYMBOL} />
);