/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-archive-16"><path fill-rule="evenodd" d="M1 2.5A1.5 1.5 0 0 1 2.5 1h11A1.5 1.5 0 0 1 15 2.5v3a1.5 1.5 0 0 1-1 1.415V12.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 12.5V6.915A1.5 1.5 0 0 1 1 5.5v-3ZM13 5H3V3h10v2Zm-1 2H4v5.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V7ZM7 8a1 1 0 0 0 0 2h2a1 1 0 1 0 0-2H7Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconArchive16: EbayIconComponent = props => (
    <EbayIcon {...props} name="archive16" __type="icon" __symbol={SYMBOL} />
);