/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-full-view-filled-16"><path d="M15 1H1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1ZM1 13h14a1 1 0 1 1 0 2H1a1 1 0 1 1 0-2Z"/></symbol>`;

export const EbayIconFullViewFilled16: EbayIconComponent = props => (
    <EbayIcon {...props} name="fullViewFilled16" __type="icon" __symbol={SYMBOL} />
);