/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-contrast-24"><path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Zm8-10a8 8 0 0 1-8 8V4a8 8 0 0 1 8 8Z"/></symbol>`;

export const EbayIconContrast24: EbayIconComponent = props => (
    <EbayIcon {...props} name="contrast24" __type="icon" __symbol={SYMBOL} />
);