/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-chat-16"><path d="M5 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M0 4a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3v1.99a.998.998 0 0 1-1.515.868L6.723 13H3a3 3 0 0 1-3-3V4Zm13 7h-2v2.234l-3.464-2.079A.995.995 0 0 0 7 11H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1Z"/></symbol>`;

export const EbayIconChat16: EbayIconComponent = props => (
    <EbayIcon {...props} name="chat16" __type="icon" __symbol={SYMBOL} />
);