/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-desktop-20"><path d="M16 2a3 3 0 0 1 3 3v7a3 3 0 0 1-3 3h-5v2h3a1 1 0 1 1 0 2H6a1 1 0 1 1 0-2h3v-2H4a3 3 0 0 1-2.996-2.846L1 12V5a3 3 0 0 1 3-3h12ZM4 4a1 1 0 0 0-1 1v7l.005.102A1 1 0 0 0 4 13h12a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H4Z"/></symbol>`;

export const EbayIconDesktop20: EbayIconComponent = props => (
    <EbayIcon {...props} name="desktop20" __type="icon" __symbol={SYMBOL} />
);