/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-sparkline-down-24"><path d="M16 18a1 1 0 1 1 0-2h3.586L13 9.414l-4.293 4.293a1 1 0 0 1-1.414 0l-6-6a1 1 0 0 1 1.414-1.414L8 11.586l4.293-4.293a1 1 0 0 1 1.414 0L21 14.586V11a1 1 0 1 1 2 0v6a1 1 0 0 1-1 1h-6Z"/></symbol>`;

export const EbayIconSparklineDown24: EbayIconComponent = props => (
    <EbayIcon {...props} name="sparklineDown24" __type="icon" __symbol={SYMBOL} />
);