/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-scan-24"><path fill-rule="evenodd" d="M0 19a3 3 0 0 0 3 3h2a1 1 0 1 0 0-2H3a1 1 0 0 1-1-1v-2a1 1 0 1 0-2 0v2ZM18 7a1 1 0 0 1 1 1v8a1 1 0 1 1-2 0V8a1 1 0 0 1 1-1Zm6 12a3 3 0 0 1-3 3h-2a1 1 0 1 1 0-2h2a1 1 0 0 0 1-1v-2a1 1 0 1 1 2 0v2ZM14 7a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0V8a1 1 0 0 1 1-1Zm-4 0a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0V8a1 1 0 0 1 1-1ZM6 7a1 1 0 0 1 1 1v8a1 1 0 1 1-2 0V8a1 1 0 0 1 1-1Zm18-2a3 3 0 0 0-3-3h-2a1 1 0 1 0 0 2h2a1 1 0 0 1 1 1v2a1 1 0 1 0 2 0V5ZM0 5a3 3 0 0 1 3-3h2a1 1 0 0 1 0 2H3a1 1 0 0 0-1 1v2a1 1 0 0 1-2 0V5Z" clip-rule="evenodd"/></symbol>`;

export const EbayIconScan24: EbayIconComponent = props => (
    <EbayIcon {...props} name="scan24" __type="icon" __symbol={SYMBOL} />
);