/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-move-16"><path d="M13.71 12.29 6.41 5H12a1 1 0 1 0 0-2H4a1 1 0 0 0-1 1v8a1 1 0 1 0 2 0V6.41l7.29 7.29a1 1 0 0 0 1.41-1.41h.01Z"/></symbol>`;

export const EbayIconMove16: EbayIconComponent = props => (
    <EbayIcon {...props} name="move16" __type="icon" __symbol={SYMBOL} />
);