/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-mobile-16"><path d="M10.5 0A2.5 2.5 0 0 1 13 2.5v11a2.5 2.5 0 0 1-2.5 2.5h-5A2.5 2.5 0 0 1 3 13.5v-11A2.5 2.5 0 0 1 5.5 0h5Zm-5 2a.5.5 0 0 0-.5.5v11a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 .5-.5v-11a.5.5 0 0 0-.5-.5h-5Zm3 9.5a.75.75 0 0 1 0 1.5h-1a.75.75 0 0 1 0-1.5h1Z"/></symbol>`;

export const EbayIconMobile16: EbayIconComponent = props => (
    <EbayIcon {...props} name="mobile16" __type="icon" __symbol={SYMBOL} />
);