/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-lock-filled-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 6a3 3 0 0 1 6 0v1H7V6ZM5 7V6a5 5 0 0 1 10 0v1a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3v-6a3 3 0 0 1 3-3Zm5 4a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1Z"/></symbol>`;

export const EbayIconLockFilled20: EbayIconComponent = props => (
    <EbayIcon {...props} name="lockFilled20" __type="icon" __symbol={SYMBOL} />
);