/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-search-similar-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 3.999a1 1 0 0 1 1-1h2a1 1 0 1 0 0-2H4a3 3 0 0 0-3 3v2a1 1 0 1 0 2 0v-2Zm16 0a3 3 0 0 0-3-3h-2a1 1 0 1 0 0 2h2a1 1 0 0 1 1 1v2a1 1 0 1 0 2 0v-2Zm-15 13a1 1 0 0 1-1-1v-2a1 1 0 1 0-2 0v2a3 3 0 0 0 3 3h2a1 1 0 1 0 0-2H4ZM10 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm0 2c1.02 0 1.967-.305 2.757-.828l3.536 3.535a1 1 0 0 0 1.414-1.414l-3.535-3.536A5 5 0 1 0 10 15Z"/></symbol>`;

export const EbayIconSearchSimilar20: EbayIconComponent = props => (
    <EbayIcon {...props} name="searchSimilar20" __type="icon" __symbol={SYMBOL} />
);