/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 18 18" id="icon-checkbox-mixed-18"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 0a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4Zm1 8a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2H5Z"/></symbol>`;

export const EbayIconCheckboxMixed18: EbayIconComponent = props => (
    <EbayIcon {...props} name="checkboxMixed18" __type="icon" __symbol={SYMBOL} />
);