// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-information-filled-20"><path d="M10 0c5.523 0 10 4.477 10 10s-4.477 10-10 10S0 15.523 0 10 4.477 0 10 0Zm0 8.5a1 1 0 0 0-1 1V14a1 1 0 1 0 2 0V9.5a1 1 0 0 0-1-1ZM10 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2Z"/></symbol>`;

export function EvoIconInformationFilled20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="informationFilled20" __symbol={SYMBOL} />;
}
