// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" fill="none" id="icon-spinner-20"><path d="M15 8a7 7 0 1 1-8.657-6.801" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" stroke="var(--color-spinner-icon-background, #3665F3)"/><path d="M9.738 1.22a7 7 0 0 1 4.574 3.754" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" stroke="var(--color-spinner-icon-foreground, #E5E5E5)"/></symbol>`;

export function EvoIconSpinner20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="spinner20" __symbol={SYMBOL} />;
}
