// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-progress-upcoming-24"><path fill-rule="evenodd" d="M12 2C6.478 2 2 6.476 2 12c0 5.522 4.478 10 10 10s10-4.478 10-10c0-5.524-4.478-10-10-10ZM0 12C0 5.372 5.373 0 12 0s12 5.372 12 12c0 6.627-5.373 12-12 12S0 18.627 0 12Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconProgressUpcoming24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="progressUpcoming24" __symbol={SYMBOL} />;
}
