// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 18 18" id="icon-checkbox-mixed-18"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 0a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4Zm1 8a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2H5Z"/></symbol>`;

export function EvoIconCheckboxMixed18(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="checkboxMixed18" __symbol={SYMBOL} />;
}
