// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-ebay-plus-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 1a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0V2a1 1 0 0 1 1-1ZM1 12a1 1 0 0 1 1-1h8a3 3 0 0 1 3 3v8a1 1 0 1 1-2 0v-8a1 1 0 0 0-1-1H2a1 1 0 0 1-1-1Zm15-1a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2h-6Z"/></symbol>`;

export function EvoIconEbayPlus24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="ebayPlus24" __symbol={SYMBOL} />;
}
