// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-folder-add-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 3a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5H8.041a1.1 1.1 0 0 1-.777-.322L5.732 3.146A.5.5 0 0 0 5.38 3H2.5ZM0 3.5A2.5 2.5 0 0 1 2.5 1h2.879a2.5 2.5 0 0 1 1.767.732L8.414 3H13.5A2.5 2.5 0 0 1 16 5.5v7a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 0 12.5v-9ZM8 6a1 1 0 0 1 1 1v1h1a1 1 0 1 1 0 2H9v1a1 1 0 1 1-2 0v-1H6a1 1 0 1 1 0-2h1V7a1 1 0 0 1 1-1Z"/></symbol>`;

export function EvoIconFolderAdd16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="folderAdd16" __symbol={SYMBOL} />;
}
