// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-download-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 2a1 1 0 1 0-2 0v9.586L5.707 8.293a1 1 0 0 0-1.414 1.414l5 5a1 1 0 0 0 1.414 0l5-5a1 1 0 0 0-1.414-1.414L11 11.586V2ZM2 17a1 1 0 1 0 0 2h16a1 1 0 1 0 0-2H2Z"/></symbol>`;

export function EvoIconDownload20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="download20" __symbol={SYMBOL} />;
}
