// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-share-ios-24"><path d="m11.293 1.293-3 3a1 1 0 0 0 1.414 1.414L11 4.414V15a1 1 0 1 0 2 0V4.414l1.293 1.293a1 1 0 1 0 1.414-1.414L12.71 1.295l-.002-.002A.98.98 0 0 0 12 1a.98.98 0 0 0-.707.293Z"/><path d="M6 8a3 3 0 0 0-3 3v9a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3v-9a3 3 0 0 0-3-3h-2a1 1 0 1 0 0 2h2a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-9a1 1 0 0 1 1-1h2a1 1 0 1 0 0-2H6Z"/></symbol>`;

export function EvoIconShareIos24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="shareIos24" __symbol={SYMBOL} />;
}
