// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-panel-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 5a1 1 0 0 1 1-1h3v12H3a1 1 0 0 1-1-1V5Zm6 11h9a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H8v12ZM3 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h14a3 3 0 0 0 3-3V5a3 3 0 0 0-3-3H3Z"/></symbol>`;

export function EvoIconPanel20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="panel20" __symbol={SYMBOL} />;
}
