// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-hanger-16"><path fill-rule="evenodd" d="M8 3a1 1 0 0 0-1 1 1 1 0 0 1-2 0 3 3 0 0 1 6 0v1a2.45 2.45 0 0 1-1.003 1.99l4.543 2.595A2.898 2.898 0 0 1 13.102 15H2.898A2.898 2.898 0 0 1 1.46 9.585l7.3-4.172A.456.456 0 0 0 9 5V4a1 1 0 0 0-1-1Zm-5.547 8.322A.898.898 0 0 0 2.898 13h10.204a.898.898 0 0 0 .445-1.678L8 8.152l-5.547 3.17Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconHanger16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="hanger16" __symbol={SYMBOL} />;
}
