// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-shoe-box-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 8V6h18v2H3Zm-.9-4A1.1 1.1 0 0 0 1 5.1v3.8a1.1 1.1 0 0 0 1 1.096V17a3 3 0 0 0 3 3h14a3 3 0 0 0 3-3V9.996A1.1 1.1 0 0 0 23 8.9V5.1A1.1 1.1 0 0 0 21.9 4H2.1ZM20 10H4v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7Z"/></symbol>`;

export function EvoIconShoeBox24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="shoeBox24" __symbol={SYMBOL} />;
}
