// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-authenticity-guarantee-filled-16"><path d="M8 0c.9 0 1.716.356 2.315.936.279.268.656.424 1.042.431a3.32 3.32 0 0 1 2.3.977c.636.636.962 1.466.976 2.3.007.386.163.763.432 1.04.579.6.935 1.417.935 2.316 0 .9-.356 1.717-.935 2.316a1.547 1.547 0 0 0-.432 1.041 3.323 3.323 0 0 1-.976 2.3 3.323 3.323 0 0 1-2.3.976 1.549 1.549 0 0 0-1.042.432C9.715 15.644 8.9 16 8 16a3.32 3.32 0 0 1-2.315-.935 1.549 1.549 0 0 0-1.042-.432 3.322 3.322 0 0 1-2.3-.976 3.322 3.322 0 0 1-.975-2.299 1.549 1.549 0 0 0-.431-1.042A3.323 3.323 0 0 1 0 8c0-.9.357-1.716.937-2.315.268-.278.424-.656.43-1.042.015-.834.34-1.664.977-2.3a3.323 3.323 0 0 1 2.299-.976 1.547 1.547 0 0 0 1.04-.431A3.324 3.324 0 0 1 8 0Zm3.207 5.793a1 1 0 0 0-1.414 0L7 8.586l-.793-.793a1 1 0 1 0-1.414 1.414l1.5 1.5a1 1 0 0 0 1.414 0l3.5-3.5a1 1 0 0 0 0-1.414Z"/></symbol>`;

export function EvoIconAuthenticityGuaranteeFilled16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="authenticityGuaranteeFilled16" __symbol={SYMBOL} />;
}
