// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-clock-fast-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M6.5 3.67a5 5 0 1 1 0 8.663 1 1 0 1 0-1 1.73 7 7 0 1 0 0-12.126 1 1 0 0 0 1 1.732ZM10 6a1 1 0 1 0-2 0v2a1 1 0 0 0 .293.707l1.5 1.5a1 1 0 0 0 1.414-1.414L10 7.587V6ZM0 6a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1Zm2 3a1 1 0 0 0 0 2h2a1 1 0 1 0 0-2H2Z"/></symbol>`;

export function EvoIconClockFast16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="clockFast16" __symbol={SYMBOL} />;
}
