// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-yuan-16"><path d="M1.35.24a1 1 0 0 1 1.41.11L8 6.462 13.24.35a1 1 0 1 1 1.52 1.302L9.316 8H12a1 1 0 1 1 0 2H9v1h3a1 1 0 1 1 0 2H9v2a1 1 0 1 1-2 0v-2H4a1 1 0 1 1 0-2h3v-1H4a1 1 0 1 1 0-2h2.683L1.24 1.65A1 1 0 0 1 1.349.24Z"/></symbol>`;

export function EvoIconYuan16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="yuan16" __symbol={SYMBOL} />;
}
