// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-pause-24"><path d="M9 5a2 2 0 1 0-4 0v14a2 2 0 1 0 4 0V5Zm10 0a2 2 0 1 0-4 0v14a2 2 0 1 0 4 0V5Z"/></symbol>`;

export function EvoIconPause24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="pause24" __symbol={SYMBOL} />;
}
