// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-chevron-right-12"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.183 10.192a.625.625 0 0 1 0-.884L7.487 6 4.183 2.692a.625.625 0 0 1 .884-.884l3.745 3.75a.625.625 0 0 1 0 .884l-3.745 3.75a.625.625 0 0 1-.884 0Z"/></symbol>`;

export function EvoIconChevronRight12(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronRight12" __symbol={SYMBOL} />;
}
