// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-play-20"><path d="m6.142 2.205 11.2 6.665a1.3 1.3 0 0 1 0 2.26l-11.2 6.665C5.21 18.35 4 17.712 4 16.665V3.335c0-1.047 1.21-1.685 2.142-1.13Z"/></symbol>`;

export function EvoIconPlay20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="play20" __symbol={SYMBOL} />;
}
