// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chevron-left-24"><path d="m6.293 11.292 8-8a1 1 0 1 1 1.414 1.415L8.414 12l7.293 7.293a1 1 0 1 1-1.414 1.414l-8-8a.996.996 0 0 1 0-1.415Z"/></symbol>`;

export function EvoIconChevronLeft24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronLeft24" __symbol={SYMBOL} />;
}
