// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chevron-down-24"><path d="M12.376 17.927a.997.997 0 0 0 .331-.22l8-8a1 1 0 0 0-1.414-1.414L12 15.586 4.707 8.293a1 1 0 0 0-1.414 1.414l8 8a1 1 0 0 0 1.083.22Z"/></symbol>`;

export function EvoIconChevronDown24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronDown24" __symbol={SYMBOL} />;
}
