// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-transaction-24"><path d="m21.707 6.707-4 4a1 1 0 0 1-1.414-1.414L18.586 7H3a1 1 0 0 1 0-2h15.586l-2.293-2.293a1 1 0 0 1 1.414-1.414l4 4a1 1 0 0 1 0 1.414ZM6.293 13.293a1 1 0 0 1 1.414 1.414L5.414 17H21a1 1 0 1 1 0 2H5.414l2.293 2.293a1 1 0 1 1-1.414 1.414l-4-4a.999.999 0 0 1 0-1.414l4-4Z"/></symbol>`;

export function EvoIconTransaction24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="transaction24" __symbol={SYMBOL} />;
}
