// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-cart-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 2a1 1 0 0 0 0 2h2.204l2.464 10.675A3 3 0 0 0 8.59 17h8.805a3 3 0 0 0 2.928-2.349l1.652-7.434A1.01 1.01 0 0 0 21 6H5.719l-.74-3.202A.999.999 0 0 0 4 2H1Zm6.617 12.225L6.18 8h13.573l-1.381 6.217a1 1 0 0 1-.976.783H8.59a1 1 0 0 1-.974-.775Z"/><path d="M8 23a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm12-2a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/></symbol>`;

export function EvoIconCart24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="cart24" __symbol={SYMBOL} />;
}
