// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-overflow-horizontal-24"><path d="M17 12a2 2 0 1 0 3.999.001A2 2 0 0 0 17 12Zm-7 0a2 2 0 1 0 3.999.001A2 2 0 0 0 10 12Zm-5 2a2 2 0 1 1-.001-3.999A2 2 0 0 1 5 14Z"/></symbol>`;

export function EvoIconOverflowHorizontal24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="overflowHorizontal24" __symbol={SYMBOL} />;
}
