// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-remove-24"><path d="M21 11H3a1 1 0 0 0 0 2h18a1 1 0 0 0 0-2Z"/></symbol>`;

export function EvoIconRemove24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="remove24" __symbol={SYMBOL} />;
}
