// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-panel-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 4a.5.5 0 0 1 .5-.5H5v9H2.5A.5.5 0 0 1 2 12V4Zm5 8.5h6.5a.5.5 0 0 0 .5-.5V4a.5.5 0 0 0-.5-.5H7v9Zm-4.5-11A2.5 2.5 0 0 0 0 4v8a2.5 2.5 0 0 0 2.5 2.5h11A2.5 2.5 0 0 0 16 12V4a2.5 2.5 0 0 0-2.5-2.5h-11Z"/></symbol>`;

export function EvoIconPanel16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="panel16" __symbol={SYMBOL} />;
}
