// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-masonry-view-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M2 1a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2Zm12 16a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1h-8ZM1 10a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V10Zm13-9a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1h-8Z"/></symbol>`;

export function EvoIconMasonryViewFilled24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="masonryViewFilled24" __symbol={SYMBOL} />;
}
