// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-chevron-up-24"><path d="m12.707 6.293 8 8a1 1 0 0 1-1.414 1.414L12 8.414l-7.293 7.293a1 1 0 0 1-1.414-1.414l8-8a1 1 0 0 1 1.414 0Z"/></symbol>`;

export function EvoIconChevronUp24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronUp24" __symbol={SYMBOL} />;
}
