// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-desktop-24"><path d="M20 2a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3h-7v3h4a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2h4v-3H4a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3h16ZM4 4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H4Z"/></symbol>`;

export function EvoIconDesktop24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="desktop24" __symbol={SYMBOL} />;
}
