// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-bar-chart-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M15 14a1 1 0 1 1-2 0V5a1 1 0 1 1 2 0v9Zm-8 0a1 1 0 1 1-2 0V8a1 1 0 1 1 2 0v6Zm3 1a1 1 0 0 0 1-1V1a1 1 0 1 0-2 0v13a1 1 0 0 0 1 1Zm-7-1a1 1 0 1 1-2 0V5a1 1 0 1 1 2 0v9Z"/></symbol>`;

export function EvoIconBarChart16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="barChart16" __symbol={SYMBOL} />;
}
