// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-credit-card-20"><path d="M17 3a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3H3a3 3 0 0 1-2.996-2.846L0 14V6a3 3 0 0 1 3-3h14ZM2 9.5V14l.005.102A1 1 0 0 0 3 15h14a1 1 0 0 0 1-1V9.5H2ZM3 5a1 1 0 0 0-1 1v1h16V6a1 1 0 0 0-1-1H3Z"/></symbol>`;

export function EvoIconCreditCard20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="creditCard20" __symbol={SYMBOL} />;
}
