// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-reply-24"><path d="M12 9c6.075 0 11 4.925 11 11v1a1 1 0 1 1-2 0v-1a9 9 0 0 0-9-9H3.414l5.293 5.293a1 1 0 1 1-1.414 1.414l-7-7a1 1 0 0 1 0-1.414l7-7a1 1 0 0 1 1.414 1.414L3.414 9H12Z"/></symbol>`;

export function EvoIconReply24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="reply24" __symbol={SYMBOL} />;
}
