// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-density-relaxed-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.8 6.5a.8.8 0 0 0-.8.8v1.4a.8.8 0 0 0 .8.8h1.4a.8.8 0 0 0 .8-.8V7.3a.8.8 0 0 0-.8-.8H1.8ZM7 7a1 1 0 0 0 0 2h7a1 1 0 1 0 0-2H7Z"/></symbol>`;

export function EvoIconDensityRelaxed16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="densityRelaxed16" __symbol={SYMBOL} />;
}
