// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-ai-filled-16"><path d="M7.212 1.637c.182-.85 1.394-.85 1.576 0l.53 2.467a3.358 3.358 0 0 0 2.578 2.578l2.467.53c.85.182.85 1.394 0 1.576l-2.467.53a3.358 3.358 0 0 0-2.578 2.578l-.53 2.467c-.182.85-1.394.85-1.576 0l-.53-2.467a3.358 3.358 0 0 0-2.578-2.578l-2.467-.53c-.85-.182-.85-1.394 0-1.576l2.467-.53a3.358 3.358 0 0 0 2.578-2.578l.53-2.467Z"/></symbol>`;

export function EvoIconAiFilled16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="aiFilled16" __symbol={SYMBOL} />;
}
