// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-pin-filled-16"><path d="M6.563.508A1 1 0 0 1 7.927.13l6.465 3.66a1 1 0 1 1-.985 1.74l-.608-.344-1.76 3.016.27 1.887c.033.235.004.474-.086.692l-.042.093-.588 1.178c-.272.543-.942.75-1.473.455l-2.077-1.155-2.376 4.146a1 1 0 1 1-1.735-.995l2.363-4.122-2.058-1.143a1.067 1.067 0 0 1-.436-1.409l.583-1.167c.14-.282.378-.505.668-.629l1.902-.816 1.628-2.985-.64-.362a1 1 0 0 1-.38-1.362Z"/></symbol>`;

export function EvoIconPinFilled16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="pinFilled16" __symbol={SYMBOL} />;
}
