// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-add-12"><path fill-rule="evenodd" clip-rule="evenodd" d="M6.75 1.75a.75.75 0 0 0-1.5 0v3.5h-3.5a.75.75 0 0 0 0 1.5h3.5v3.5a.75.75 0 0 0 1.5 0v-3.5h3.5a.75.75 0 0 0 0-1.5h-3.5v-3.5Z"/></symbol>`;

export function EvoIconAdd12(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="add12" __symbol={SYMBOL} />;
}
