// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-chevron-down-20"><path d="M9.293 15.707a.999.999 0 0 0 1.414 0l7-7a1 1 0 0 0-1.414-1.414L10 13.586 3.707 7.293a1 1 0 0 0-1.414 1.414l7 7Z"/></symbol>`;

export function EvoIconChevronDown20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronDown20" __symbol={SYMBOL} />;
}
