// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-play-24"><path d="m6.754 2.256 14.4 8.331c1.128.653 1.128 2.173 0 2.826l-14.4 8.331C5.555 22.438 4 21.64 4 20.331V3.67c0-1.31 1.555-2.108 2.754-1.414Z"/></symbol>`;

export function EvoIconPlay24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="play24" __symbol={SYMBOL} />;
}
