// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-credit-card-24"><path d="M20 4a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3h16ZM3 11v6a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-6H3Zm1-5a1 1 0 0 0-1 1v1h18V7a1 1 0 0 0-1-1H4Z"/></symbol>`;

export function EvoIconCreditCard24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="creditCard24" __symbol={SYMBOL} />;
}
