// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-attention-filled-24"><path d="M12 0c6.625.006 11.994 5.375 12 12 0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0Zm0 16a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm1-3V7a1 1 0 1 0-2 0v6a1 1 0 1 0 2 0Z"/></symbol>`;

export function EvoIconAttentionFilled24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="attentionFilled24" __symbol={SYMBOL} />;
}
