// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-upload-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l7 7a1 1 0 0 1-1.414 1.414L13 4.414V17a1 1 0 1 1-2 0V4.414L5.707 9.707a1 1 0 0 1-1.414-1.414l7-7ZM2 21a1 1 0 1 0 0 2h20a1 1 0 1 0 0-2H2Z"/></symbol>`;

export function EvoIconUpload24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="upload24" __symbol={SYMBOL} />;
}
