// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-arrow-up-24"><path d="m11.29 2.296-7.996 7.998a1.004 1.004 0 0 0 1.419 1.42L11 5.414V21a1 1 0 0 0 1.998 0V5.415l6.287 6.298a1 1 0 0 0 1.42 0 1.001 1.001 0 0 0 0-1.42l-7.996-7.997a1 1 0 0 0-1.42 0Z"/></symbol>`;

export function EvoIconArrowUp24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowUp24" __symbol={SYMBOL} />;
}
