// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-bookmark-filled-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 4a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v18a1 1 0 0 1-1.707.707L12 16.414l-6.293 6.293A1 1 0 0 1 4 22V4Z"/></symbol>`;

export function EvoIconBookmarkFilled24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="bookmarkFilled24" __symbol={SYMBOL} />;
}
