// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-mobile-20"><path d="M13 1a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h6ZM7 3a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H7Zm3.75 11a1 1 0 1 1 0 2h-1.5a1 1 0 1 1 0-2h1.5Z"/></symbol>`;

export function EvoIconMobile20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="mobile20" __symbol={SYMBOL} />;
}
