// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-chevron-up-12"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.808 7.816c.244.245.64.245.884.001L6 4.51l3.308 3.307a.625.625 0 1 0 .884-.885l-3.75-3.75a.625.625 0 0 0-.884.001l-3.75 3.749a.626.626 0 0 0 0 .884Z"/></symbol>`;

export function EvoIconChevronUp12(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronUp12" __symbol={SYMBOL} />;
}
