// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-satchel-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.5 1A2.5 2.5 0 0 0 2 3.5v9A2.5 2.5 0 0 0 4.5 15h7a2.5 2.5 0 0 0 2.5-2.5v-9A2.5 2.5 0 0 0 11.5 1h-7ZM4 3.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v.703L8 6 4 4.203V3.5Zm0 2.896V12.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V6.396L8.82 7.824a2 2 0 0 1-1.64 0L4 6.396Z"/></symbol>`;

export function EvoIconSatchel16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="satchel16" __symbol={SYMBOL} />;
}
