// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-categories-24"><path d="M17.5 11a4.498 4.498 0 0 1-3.182-7.682A4.5 4.5 0 0 1 22 6.5a4.5 4.5 0 0 1-4.5 4.5Zm1.768-6.268a2.5 2.5 0 1 0-3.535 3.536 2.5 2.5 0 0 0 3.535-3.536ZM6.5 11a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9Zm0-7a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5ZM2.343 19.222a4.5 4.5 0 1 0 8.313-3.445 4.5 4.5 0 0 0-8.313 3.445ZM4 17.5a2.5 2.5 0 1 1 5 0 2.5 2.5 0 0 1-5 0ZM17.5 22a4.498 4.498 0 0 1-3.182-7.682A4.5 4.5 0 0 1 22 17.5a4.5 4.5 0 0 1-4.5 4.5Zm0-7a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Z"/></symbol>`;

export function EvoIconCategories24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="categories24" __symbol={SYMBOL} />;
}
