// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-wallet-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M4 4a1 1 0 0 0 0 2h15V5a1 1 0 0 0-1-1H4ZM1 5a3 3 0 0 1 3-3h14a3 3 0 0 1 3 3v1.17c1.165.413 2 1.524 2 2.83v10a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V5Zm5 15h14a1 1 0 0 0 1-1v-2h-6a3 3 0 1 1 0-6h6V9a1 1 0 0 0-1-1H4c-.35 0-.687-.06-1-.17V19a1 1 0 0 0 1 1h2Zm9-5h6v-2h-6a1 1 0 1 0 0 2Z"/></symbol>`;

export function EvoIconWallet24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="wallet24" __symbol={SYMBOL} />;
}
