// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-arrow-right-16"><path d="M14.92 8.38a1 1 0 0 0-.22-1.09l-6-6a1 1 0 1 0-1.41 1.42L11.59 7H2a1 1 0 1 0 0 2h9.59l-4.3 4.29A1 1 0 1 0 8.7 14.7l6-6a1 1 0 0 0 .22-.32Z"/></symbol>`;

export function EvoIconArrowRight16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowRight16" __symbol={SYMBOL} />;
}
