// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-reply-16"><path d="M8 6a7 7 0 0 1 7 7 1 1 0 1 1-2 0 5 5 0 0 0-5-5H3.414l2.293 2.293a1 1 0 1 1-1.414 1.414l-4-4a1 1 0 0 1 0-1.414l4-4a1 1 0 0 1 1.414 1.414L3.414 6H8Z"/></symbol>`;

export function EvoIconReply16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="reply16" __symbol={SYMBOL} />;
}
