// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-zoom-in-24"><path fill-rule="evenodd" d="M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm0 2a8.962 8.962 0 0 0 5.618-1.968l5.675 5.675a1 1 0 0 0 1.414-1.414l-5.675-5.675A9 9 0 1 0 10 19Zm1-12a1 1 0 1 0-2 0v2H7a1 1 0 0 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2V7Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconZoomIn24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="zoomIn24" __symbol={SYMBOL} />;
}
