// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-menu-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.5 2a1 1 0 0 0 0 2h11a1 1 0 1 0 0-2h-11Zm-1 6a1 1 0 0 1 1-1h11a1 1 0 1 1 0 2h-11a1 1 0 0 1-1-1Zm0 5a1 1 0 0 1 1-1h11a1 1 0 1 1 0 2h-11a1 1 0 0 1-1-1Z"/></symbol>`;

export function EvoIconMenu16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="menu16" __symbol={SYMBOL} />;
}
