// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-stepper-current-24"><path fill-rule="evenodd" d="M2 12C2 6.476 6.478 2 12 2s10 4.476 10 10c0 5.522-4.478 10-10 10S2 17.522 2 12ZM12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12s12-5.373 12-12c0-6.628-5.373-12-12-12Zm0 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" clip-rule="evenodd" fill="var(--progress-stepper-current-icon, var(--color-background-accent))"/></symbol>`;

export function EvoIconStepperCurrent24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="stepperCurrent24" __symbol={SYMBOL} />;
}
