// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-overflow-horizontal-20"><path d="M16 11.75a1.75 1.75 0 1 1 0-3.5 1.75 1.75 0 0 1 0 3.5Zm-6 0a1.75 1.75 0 1 1 0-3.5 1.75 1.75 0 0 1 0 3.5Zm-6 0a1.75 1.75 0 1 1 0-3.5 1.75 1.75 0 0 1 0 3.5Z"/></symbol>`;

export function EvoIconOverflowHorizontal20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="overflowHorizontal20" __symbol={SYMBOL} />;
}
