// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-contrast-24"><path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Zm8-10a8 8 0 0 1-8 8V4a8 8 0 0 1 8 8Z"/></symbol>`;

export function EvoIconContrast24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="contrast24" __symbol={SYMBOL} />;
}
