// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-full-view-16"><path d="M15 1H1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1Zm-1 8H2V3h12v6ZM1 13h14a1 1 0 1 1 0 2H1a1 1 0 1 1 0-2Z"/></symbol>`;

export function EvoIconFullView16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="fullView16" __symbol={SYMBOL} />;
}
