// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-arrow-left-24"><path d="M21 11H5.41l6.3-6.29a1.003 1.003 0 1 0-1.42-1.42l-8 8a1.001 1.001 0 0 0 0 1.42l8 8a1.001 1.001 0 0 0 1.42 0 1.001 1.001 0 0 0 0-1.42L5.41 13H21a1 1 0 0 0 0-2Z"/></symbol>`;

export function EvoIconArrowLeft24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowLeft24" __symbol={SYMBOL} />;
}
