// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-list-view-24"><path d="M3 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm19 1H7a1 1 0 0 1 0-2h15a1 1 0 0 1 0 2ZM2 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm5-2h15a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2ZM2 21a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm5-2h15a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2Z"/></symbol>`;

export function EvoIconListView24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="listView24" __symbol={SYMBOL} />;
}
