// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-sparkline-down-16"><path d="M10 12a1 1 0 1 1 0-2h1.586L9 7.414 6.707 9.707a1 1 0 0 1-1.414 0l-4-4a1 1 0 0 1 1.414-1.414L6 7.586l2.293-2.293a1 1 0 0 1 1.414 0L13 8.586V7a1 1 0 1 1 2 0v4a1 1 0 0 1-1 1h-4Z"/></symbol>`;

export function EvoIconSparklineDown16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="sparklineDown16" __symbol={SYMBOL} />;
}
