// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-download-16"><path d="M8 1a1 1 0 0 1 1 1v5.586l2.293-2.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-4-4a1 1 0 0 1 1.414-1.414L7 7.586V2a1 1 0 0 1 1-1Z"/><path fill-rule="evenodd" d="M1 14a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H2a1 1 0 0 1-1-1Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconDownload16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="download16" __symbol={SYMBOL} />;
}
