// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-arrow-down-24"><path d="M11 3v15.585l-6.287-6.298a1.002 1.002 0 0 0-1.679.45c-.093.347.006.716.26.97l7.996 7.997a1 1 0 0 0 1.419 0l7.995-7.998a1.001 1.001 0 0 0 0-1.42 1 1 0 0 0-1.419 0l-6.286 6.299V3a1 1 0 0 0-2 0Z"/></symbol>`;

export function EvoIconArrowDown24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowDown24" __symbol={SYMBOL} />;
}
