// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 35 25" fill="none" id="icon-ccd-top"><path d="M0.5 25V13.5H34.5V25" stroke-width="1"/><path d="M6.5 13V0.5H10.5V13" stroke-width="1"/><path d="M24.5 13V0.5H28.5V13" stroke-width="1"/></symbol>`;

export function EvoIconCcdTop(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="ccdTop" __symbol={SYMBOL} />;
}
