// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-overflow-vertical-24"><path d="M12 7a2 2 0 1 0 .001-3.999A2 2 0 0 0 12 7Zm0 7a2 2 0 1 0 .001-3.999A2 2 0 0 0 12 14Zm2 5a2 2 0 1 1-3.999.001A2 2 0 0 1 14 19Z"/></symbol>`;

export function EvoIconOverflowVertical24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="overflowVertical24" __symbol={SYMBOL} />;
}
