// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-return-16"><path d="M6.707 2.707a1 1 0 0 0-1.414-1.414l-3 3a.997.997 0 0 0 0 1.414l3 3a1 1 0 1 0 1.414-1.414L5.414 6H9c2.31 0 4 1.663 4 3.5 0 1.836-1.69 3.5-4 3.5H4a1 1 0 1 0 0 2h5c3.212 0 6-2.366 6-5.5S12.212 4 9 4H5.414l1.293-1.293Z"/></symbol>`;

export function EvoIconReturn16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="return16" __symbol={SYMBOL} />;
}
