// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-tick-24"><path d="M10 17a.999.999 0 0 1-.71-.29l-4-4A1 1 0 0 1 6.7 11.3l3.3 3.29 7.29-7.29a1 1 0 0 1 1.41 1.41l-8 8a.999.999 0 0 1-.7.29Z"/></symbol>`;

export function EvoIconTick24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="tick24" __symbol={SYMBOL} />;
}
