// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-overflow-vertical-20"><path d="M11.75 4a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0Zm0 6a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0Zm0 6a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0Z"/></symbol>`;

export function EvoIconOverflowVertical20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="overflowVertical20" __symbol={SYMBOL} />;
}
