// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-feedback-negative-16"><path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0ZM5 7a1 1 0 0 0 0 2h6a1 1 0 1 0 0-2H5Z"/></symbol>`;

export function EvoIconFeedbackNegative16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="feedbackNegative16" __symbol={SYMBOL} />;
}
