// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-exclude-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.523 3.11a6 6 0 0 1 8.367 8.367L4.524 3.108ZM3.11 4.522a6 6 0 0 0 8.367 8.367L3.11 4.524ZM8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0Z"/></symbol>`;

export function EvoIconExclude16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="exclude16" __symbol={SYMBOL} />;
}
