// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-bar-chart-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 21a1 1 0 1 0 2 0V8a1 1 0 1 0-2 0v13Zm5.333 0a1 1 0 1 0 2 0v-9a1 1 0 1 0-2 0v9ZM20 22a1 1 0 0 1-1-1V8a1 1 0 1 1 2 0v13a1 1 0 0 1-1 1Zm-6.334-1a1 1 0 1 0 2 0V2a1 1 0 1 0-2 0v19Z"/></symbol>`;

export function EvoIconBarChart24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="barChart24" __symbol={SYMBOL} />;
}
