// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-overflow-horizontal-16"><path d="M11.5 8a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0Zm-10 0a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0ZM8 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Z"/></symbol>`;

export function EvoIconOverflowHorizontal16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="overflowHorizontal16" __symbol={SYMBOL} />;
}
