// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-chevron-up-16"><path d="m8.707 3.293 6 6a1 1 0 0 1-1.414 1.414L8 5.414l-5.293 5.293a1 1 0 0 1-1.414-1.414l6-6a1 1 0 0 1 1.414 0Z"/></symbol>`;

export function EvoIconChevronUp16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="chevronUp16" __symbol={SYMBOL} />;
}
