// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-mobile-16"><path d="M10.5 0A2.5 2.5 0 0 1 13 2.5v11a2.5 2.5 0 0 1-2.5 2.5h-5A2.5 2.5 0 0 1 3 13.5v-11A2.5 2.5 0 0 1 5.5 0h5Zm-5 2a.5.5 0 0 0-.5.5v11a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 .5-.5v-11a.5.5 0 0 0-.5-.5h-5Zm3 9.5a.75.75 0 0 1 0 1.5h-1a.75.75 0 0 1 0-1.5h1Z"/></symbol>`;

export function EvoIconMobile16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="mobile16" __symbol={SYMBOL} />;
}
