// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-panel-open-20"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 5a3 3 0 0 1 3-3h14a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3V5Zm3-1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h2V4H3Zm14 12H7V4h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1Zm-1.315-5.271-2.061 2.061a1 1 0 0 1-1.414-1.414l.375-.376H10a1 1 0 1 1 0-2h2.585l-.375-.376a1 1 0 1 1 1.414-1.414l2.061 2.061a.994.994 0 0 1 .313.67.998.998 0 0 1-.29.766l-.023.022Z"/></symbol>`;

export function EvoIconPanelOpen20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="panelOpen20" __symbol={SYMBOL} />;
}
