// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-play-filled-16-colored"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16Z" fill="#fff" fill-opacity=".88"/><path d="M11.514 8.857a1 1 0 0 0 0-1.714l-5-3A1 1 0 0 0 5 5v6a1 1 0 0 0 1.514.857l5-3Z" fill="#191919"/></symbol>`;

export function EvoIconPlayFilled16Colored(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="playFilled16Colored" __symbol={SYMBOL} />;
}
