// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-feedback-positive-16"><path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0Zm0 4a1 1 0 0 0-1 1v2H5a1 1 0 0 0 0 2h2v2a1 1 0 1 0 2 0V9h2a1 1 0 0 0 0-2H9V5a1 1 0 0 0-1-1Z"/></symbol>`;

export function EvoIconFeedbackPositive16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="feedbackPositive16" __symbol={SYMBOL} />;
}
