// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-arrow-up-16"><path d="M8.354 1.075a.994.994 0 0 0-1.086.22L1.29 7.297a1.004 1.004 0 0 0 .005 1.416.994.994 0 0 0 1.41-.005l4.274-4.302V14c0 .552.446 1 .997 1 .55 0 .996-.448.996-1V4.406l4.275 4.302a.994.994 0 0 0 1.725-.417 1.003 1.003 0 0 0-.32-.994L8.673 1.295a.996.996 0 0 0-.319-.22Z"/></symbol>`;

export function EvoIconArrowUp16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowUp16" __symbol={SYMBOL} />;
}
