// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-sparkline-down-24"><path d="M16 18a1 1 0 1 1 0-2h3.586L13 9.414l-4.293 4.293a1 1 0 0 1-1.414 0l-6-6a1 1 0 0 1 1.414-1.414L8 11.586l4.293-4.293a1 1 0 0 1 1.414 0L21 14.586V11a1 1 0 1 1 2 0v6a1 1 0 0 1-1 1h-6Z"/></symbol>`;

export function EvoIconSparklineDown24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="sparklineDown24" __symbol={SYMBOL} />;
}
