// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-sparkline-up-24"><path d="M16 6a1 1 0 1 0 0 2h3.586L13 14.586l-4.293-4.293a1 1 0 0 0-1.414 0l-6 6a1 1 0 1 0 1.414 1.414L8 12.414l4.293 4.293a1 1 0 0 0 1.414 0L21 9.414V13a1 1 0 1 0 2 0V7a1 1 0 0 0-1-1h-6Z"/></symbol>`;

export function EvoIconSparklineUp24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="sparklineUp24" __symbol={SYMBOL} />;
}
