// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-filter-24"><path d="M3 7a1 1 0 0 1 1-1h16a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1Zm3 5a1 1 0 0 1 1-1h10a1 1 0 1 1 0 2H7a1 1 0 0 1-1-1Zm4 4a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2h-4Z"/></symbol>`;

export function EvoIconFilter24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="filter24" __symbol={SYMBOL} />;
}
