// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 38 24" id="icon-general-card-24-colored"><rect x=".5" y=".5" width="37" height="23" rx="1.5" fill="#fff" stroke="#000" stroke-width="1"/><rect x="28.333" y="17.667" width="4.667" height=".667" rx=".333" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".667"/><rect x="20.333" y="17.667" width="4.667" height=".667" rx=".333" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".667"/><rect x="12.333" y="17.667" width="4.667" height=".667" rx=".333" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".667"/><rect x="4.333" y="17.667" width="4.667" height=".667" rx=".333" fill="#A2A2A2" stroke="#A2A2A2" stroke-width=".667"/><rect x="4.667" y="7.333" width="6.667" height="4" rx=".667" fill="#A2A2A2" stroke="#A2A2A2" stroke-width="1.333"/></symbol>`;

export function EvoIconGeneralCard24Colored(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="generalCard24Colored" __symbol={SYMBOL} />;
}
