// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-remove-12"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 6a.75.75 0 0 1 .75-.75h8.5a.75.75 0 0 1 0 1.5h-8.5A.75.75 0 0 1 1 6Z"/></symbol>`;

export function EvoIconRemove12(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="remove12" __symbol={SYMBOL} />;
}
