// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-density-row-compact-24"><path d="M20 2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3h16ZM4 4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H4Zm13 11a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2h10Zm0-4a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2h10Zm0-4a1 1 0 1 1 0 2H7a1 1 0 0 1 0-2h10Z"/></symbol>`;

export function EvoIconDensityRowCompact24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="densityRowCompact24" __symbol={SYMBOL} />;
}
