// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-arrow-down-16"><path d="M7.028 2v9.59l-4.307-4.3a1.011 1.011 0 0 0-1.426 0 1.001 1.001 0 0 0 0 1.42l6.024 6a1.007 1.007 0 0 0 1.416 0l6.024-6a.997.997 0 0 0-.053-1.358 1.007 1.007 0 0 0-1.363-.052l-4.307 4.29V2c0-.552-.45-1-1.004-1-.555 0-1.004.448-1.004 1Z"/></symbol>`;

export function EvoIconArrowDown16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowDown16" __symbol={SYMBOL} />;
}
