// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-negative-filled-16"><path fill-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16ZM5.293 5.293a1 1 0 0 1 1.414 0L8 6.586l1.293-1.293a1 1 0 0 1 1.414 1.414L9.414 8l1.293 1.293a1 1 0 0 1-1.414 1.414L8 9.414l-1.293 1.293a1 1 0 0 1-1.414-1.414L6.586 8 5.293 6.707a1 1 0 0 1 0-1.414Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconNegativeFilled16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="negativeFilled16" __symbol={SYMBOL} />;
}
