// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-swap-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.207.793a1 1 0 1 0-1.414 1.414L15.586 4H8a7 7 0 0 0-7 7v4a1 1 0 1 0 2 0v-4a5 5 0 0 1 5-5h7.586l-1.793 1.793a1 1 0 0 0 1.414 1.414l3.5-3.5a1 1 0 0 0 0-1.414l-3.5-3.5Zm-5 15.414a1 1 0 0 0-1.414-1.414l-3.5 3.5a1 1 0 0 0 0 1.414l3.5 3.5a1 1 0 0 0 1.414-1.414L8.414 20H16a7 7 0 0 0 7-7V9a1 1 0 1 0-2 0v4a5 5 0 0 1-5 5H8.414l1.793-1.793Z"/></symbol>`;

export function EvoIconSwap24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="swap24" __symbol={SYMBOL} />;
}
