// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 40 40" id="icon-avatar-signed-out"><circle cx="20" cy="20" r="20" fill="var(--color-background-secondary, #F7F7F7)"/><circle cx="20" cy="17.5" r="8.333" fill="var(--color-foreground-secondary, #707070)"/><path d="M7.67 35.748c2-4.84 6.767-8.248 12.33-8.248s10.33 3.407 12.33 8.249A19.914 19.914 0 0 1 20 40a19.914 19.914 0 0 1-12.33-4.252Z" fill="var(--color-foreground-secondary, #707070)"/></symbol>`;

export function EvoIconAvatarSignedOut(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="avatarSignedOut" __symbol={SYMBOL} />;
}
