// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-share-android-20"><path fill-rule="evenodd" d="M15 7a3 3 0 1 0-2.98-2.653L5.865 7.65a3 3 0 1 0 0 4.7l6.155 3.303a3 3 0 1 0 .882-1.797l-5.973-3.205a3.01 3.01 0 0 0 0-1.303l5.972-3.204A2.99 2.99 0 0 0 15 7Zm0-2a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm0 12a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM5 10a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconShareAndroid20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="shareAndroid20" __symbol={SYMBOL} />;
}
