// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-text-size-24"><path d="M15 5a1 1 0 1 1 0 2h-5v13l-.005.102a1 1 0 0 1-1.99 0L8 20V7H3a1 1 0 0 1 0-2h12Zm6.102 5.005a1 1 0 0 1 0 1.99L21 12h-3v8a1 1 0 1 1-2 0v-8h-3a1 1 0 1 1 0-2h8l.102.005Z"/></symbol>`;

export function EvoIconTextSize24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="textSize24" __symbol={SYMBOL} />;
}
