// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-sparkline-up-20"><path d="M13 5a1 1 0 1 0 0 2h2.586L11 11.586 7.707 8.293a1 1 0 0 0-1.414 0l-5 5a1 1 0 1 0 1.414 1.414L7 10.414l3.293 3.293a1 1 0 0 0 1.414 0L17 8.414V11a1 1 0 1 0 2 0V6a1 1 0 0 0-1-1h-5Z"/></symbol>`;

export function EvoIconSparklineUp20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="sparklineUp20" __symbol={SYMBOL} />;
}
