// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-zoom-out-24"><path fill-rule="evenodd" d="M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm0 2a8.962 8.962 0 0 0 5.618-1.968l5.675 5.675a1 1 0 0 0 1.414-1.414l-5.675-5.675A9 9 0 1 0 10 19ZM7 9a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2H7Z" clip-rule="evenodd"/></symbol>`;

export function EvoIconZoomOut24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="zoomOut24" __symbol={SYMBOL} />;
}
