// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-arrow-right-20"><path d="M9.293 2.293a1 1 0 0 0 0 1.414L14.586 9H3a1 1 0 1 0 0 2h11.586l-5.293 5.293a1 1 0 1 0 1.414 1.414l7-7a1 1 0 0 0 0-1.414l-7-7a1 1 0 0 0-1.414 0Z"/></symbol>`;

export function EvoIconArrowRight20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="arrowRight20" __symbol={SYMBOL} />;
}
