// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 13 16" id="icon-trend-down-16-fit"><path d="m10.862 5.503-3.516 6.003a1 1 0 0 1-1.728-.004L2.136 5.5A.998.998 0 0 1 3.001 4h6.998a.998.998 0 0 1 .863 1.503Z"/></symbol>`;

export function EvoIconTrendDown16Fit(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="trendDown16Fit" __symbol={SYMBOL} />;
}
