// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-bookmark-filled-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 3.5A2.5 2.5 0 0 1 5.5 1h5A2.5 2.5 0 0 1 13 3.5V14a1 1 0 0 1-1.707.707L8 11.414l-3.293 3.293A1 1 0 0 1 3 14V3.5Z"/></symbol>`;

export function EvoIconBookmarkFilled16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="bookmarkFilled16" __symbol={SYMBOL} />;
}
