// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-full-view-24"><path d="M22 3H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h20a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1Zm-1 12H3V5h18v10ZM2 19h20a1 1 0 0 1 0 2H2a1 1 0 0 1 0-2Z"/></symbol>`;

export function EvoIconFullView24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="fullView24" __symbol={SYMBOL} />;
}
