// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-download-24"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 1a1 1 0 0 1 1 1v12.586l5.293-5.293a1 1 0 1 1 1.414 1.414l-7 7a1 1 0 0 1-1.414 0l-7-7a1 1 0 0 1 1.414-1.414L11 14.586V2a1 1 0 0 1 1-1ZM2 21a1 1 0 1 0 0 2h20a1 1 0 1 0 0-2H2Z"/></symbol>`;

export function EvoIconDownload24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="download24" __symbol={SYMBOL} />;
}
