// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import type { ComponentProps } from 'react';
import type { EvoIcon } from '../icon';

export type EvoIconComponentProps = Omit<ComponentProps<typeof EvoIcon>, '__name' | '__symbol'>;
