on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["build"]
    branches: ["main"]
    types:
      - completed

concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    # Sets permissions of the GITHUB_TOKEN to allow opening release PR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm i
      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run release
          commit: "ci: release"
          title: "ci: release"
          commitMode: "github-api"
        env:
          # Disable husky
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
